package SPDX.Licenses is

   pragma Style_Checks (Off); --  Genrated code

   Version : constant String :="3.10-14-g0fb8a59";

   type Id is (
               Id_0BSD,
               AAL,
               ADSL,
               AFL_1_1,
               AFL_1_2,
               AFL_2_0,
               AFL_2_1,
               AFL_3_0,
               AGPL_1_0_only,
               AGPL_1_0_or_later,
               AGPL_3_0_only,
               AGPL_3_0_or_later,
               AMDPLPA,
               AML,
               AMPAS,
               ANTLR_PD,
               APAFML,
               APL_1_0,
               APSL_1_0,
               APSL_1_1,
               APSL_1_2,
               APSL_2_0,
               Abstyles,
               Adobe_2006,
               Adobe_Glyph,
               Afmparse,
               Aladdin,
               Apache_1_0,
               Apache_1_1,
               Apache_2_0,
               Artistic_1_0,
               Artistic_1_0_Perl,
               Artistic_1_0_cl8,
               Artistic_2_0,
               BSD_1_Clause,
               BSD_2_Clause,
               BSD_2_Clause_Patent,
               BSD_2_Clause_Views,
               BSD_3_Clause,
               BSD_3_Clause_Attribution,
               BSD_3_Clause_Clear,
               BSD_3_Clause_LBNL,
               BSD_3_Clause_No_Nuclear_License,
               BSD_3_Clause_No_Nuclear_License_2014,
               BSD_3_Clause_No_Nuclear_Warranty,
               BSD_3_Clause_Open_MPI,
               BSD_4_Clause,
               BSD_4_Clause_UC,
               BSD_Protection,
               BSD_Source_Code,
               BSL_1_0,
               Bahyph,
               Barr,
               Beerware,
               BitTorrent_1_0,
               BitTorrent_1_1,
               BlueOak_1_0_0,
               Borceux,
               CAL_1_0,
               CAL_1_0_Combined_Work_Exception,
               CATOSL_1_1,
               CC_BY_1_0,
               CC_BY_2_0,
               CC_BY_2_5,
               CC_BY_3_0,
               CC_BY_3_0_AT,
               CC_BY_4_0,
               CC_BY_NC_1_0,
               CC_BY_NC_2_0,
               CC_BY_NC_2_5,
               CC_BY_NC_3_0,
               CC_BY_NC_4_0,
               CC_BY_NC_ND_1_0,
               CC_BY_NC_ND_2_0,
               CC_BY_NC_ND_2_5,
               CC_BY_NC_ND_3_0,
               CC_BY_NC_ND_3_0_IGO,
               CC_BY_NC_ND_4_0,
               CC_BY_NC_SA_1_0,
               CC_BY_NC_SA_2_0,
               CC_BY_NC_SA_2_5,
               CC_BY_NC_SA_3_0,
               CC_BY_NC_SA_4_0,
               CC_BY_ND_1_0,
               CC_BY_ND_2_0,
               CC_BY_ND_2_5,
               CC_BY_ND_3_0,
               CC_BY_ND_4_0,
               CC_BY_SA_1_0,
               CC_BY_SA_2_0,
               CC_BY_SA_2_5,
               CC_BY_SA_3_0,
               CC_BY_SA_3_0_AT,
               CC_BY_SA_4_0,
               CC_PDDC,
               CC0_1_0,
               CDDL_1_0,
               CDDL_1_1,
               CDLA_Permissive_1_0,
               CDLA_Sharing_1_0,
               CECILL_1_0,
               CECILL_1_1,
               CECILL_2_0,
               CECILL_2_1,
               CECILL_B,
               CECILL_C,
               CERN_OHL_1_1,
               CERN_OHL_1_2,
               CERN_OHL_P_2_0,
               CERN_OHL_S_2_0,
               CERN_OHL_W_2_0,
               CNRI_Jython,
               CNRI_Python,
               CNRI_Python_GPL_Compatible,
               CPAL_1_0,
               CPL_1_0,
               CPOL_1_02,
               CUA_OPL_1_0,
               Caldera,
               ClArtistic,
               Condor_1_1,
               Crossword,
               CrystalStacker,
               Cube,
               D_FSL_1_0,
               DOC,
               DSDP,
               Dotseqn,
               ECL_1_0,
               ECL_2_0,
               EFL_1_0,
               EFL_2_0,
               EPICS,
               EPL_1_0,
               EPL_2_0,
               EUDatagrid,
               EUPL_1_0,
               EUPL_1_1,
               EUPL_1_2,
               Entessa,
               ErlPL_1_1,
               Eurosym,
               FSFAP,
               FSFUL,
               FSFULLR,
               FTL,
               Fair,
               Frameworx_1_0,
               FreeImage,
               GFDL_1_1_invariants_only,
               GFDL_1_1_invariants_or_later,
               GFDL_1_1_no_invariants_only,
               GFDL_1_1_no_invariants_or_later,
               GFDL_1_1_only,
               GFDL_1_1_or_later,
               GFDL_1_2_invariants_only,
               GFDL_1_2_invariants_or_later,
               GFDL_1_2_no_invariants_only,
               GFDL_1_2_no_invariants_or_later,
               GFDL_1_2_only,
               GFDL_1_2_or_later,
               GFDL_1_3_invariants_only,
               GFDL_1_3_invariants_or_later,
               GFDL_1_3_no_invariants_only,
               GFDL_1_3_no_invariants_or_later,
               GFDL_1_3_only,
               GFDL_1_3_or_later,
               GL2PS,
               GLWTPL,
               GPL_1_0_only,
               GPL_1_0_or_later,
               GPL_2_0_only,
               GPL_2_0_or_later,
               GPL_3_0_only,
               GPL_3_0_or_later,
               Giftware,
               Glide,
               Glulxe,
               HPND,
               HPND_sell_variant,
               HaskellReport,
               Hippocratic_2_1,
               IBM_pibs,
               ICU,
               IJG,
               IPA,
               IPL_1_0,
               ISC,
               ImageMagick,
               Imlib2,
               Info_ZIP,
               Intel,
               Intel_ACPI,
               Interbase_1_0,
               JPNIC,
               JSON,
               JasPer_2_0,
               LAL_1_2,
               LAL_1_3,
               LGPL_2_0_only,
               LGPL_2_0_or_later,
               LGPL_2_1_only,
               LGPL_2_1_or_later,
               LGPL_3_0_only,
               LGPL_3_0_or_later,
               LGPLLR,
               LPL_1_0,
               LPL_1_02,
               LPPL_1_0,
               LPPL_1_1,
               LPPL_1_2,
               LPPL_1_3a,
               LPPL_1_3c,
               Latex2e,
               Leptonica,
               LiLiQ_P_1_1,
               LiLiQ_R_1_1,
               LiLiQ_Rplus_1_1,
               Libpng,
               Linux_OpenIB,
               MIT,
               MIT_0,
               MIT_CMU,
               MIT_advertising,
               MIT_enna,
               MIT_feh,
               MITNFA,
               MPL_1_0,
               MPL_1_1,
               MPL_2_0,
               MPL_2_0_no_copyleft_exception,
               MS_PL,
               MS_RL,
               MTLL,
               MakeIndex,
               MirOS,
               Motosoto,
               MulanPSL_1_0,
               MulanPSL_2_0,
               Multics,
               Mup,
               NASA_1_3,
               NBPL_1_0,
               NCGL_UK_2_0,
               NCSA,
               NGPL,
               NIST_PD,
               NIST_PD_fallback,
               NLOD_1_0,
               NLPL,
               NOSL,
               NPL_1_0,
               NPL_1_1,
               NPOSL_3_0,
               NRL,
               NTP,
               NTP_0,
               Naumen,
               Net_SNMP,
               NetCDF,
               Newsletr,
               Nokia,
               Noweb,
               O_UDA_1_0,
               OCCT_PL,
               OCLC_2_0,
               ODC_By_1_0,
               ODbL_1_0,
               OFL_1_0,
               OFL_1_0_RFN,
               OFL_1_0_no_RFN,
               OFL_1_1,
               OFL_1_1_RFN,
               OFL_1_1_no_RFN,
               OGC_1_0,
               OGL_Canada_2_0,
               OGL_UK_1_0,
               OGL_UK_2_0,
               OGL_UK_3_0,
               OGTSL,
               OLDAP_1_1,
               OLDAP_1_2,
               OLDAP_1_3,
               OLDAP_1_4,
               OLDAP_2_0,
               OLDAP_2_0_1,
               OLDAP_2_1,
               OLDAP_2_2,
               OLDAP_2_2_1,
               OLDAP_2_2_2,
               OLDAP_2_3,
               OLDAP_2_4,
               OLDAP_2_5,
               OLDAP_2_6,
               OLDAP_2_7,
               OLDAP_2_8,
               OML,
               OPL_1_0,
               OSET_PL_2_1,
               OSL_1_0,
               OSL_1_1,
               OSL_2_0,
               OSL_2_1,
               OSL_3_0,
               OpenSSL,
               PDDL_1_0,
               PHP_3_0,
               PHP_3_01,
               PSF_2_0,
               Parity_6_0_0,
               Parity_7_0_0,
               Plexus,
               PolyForm_Noncommercial_1_0_0,
               PolyForm_Small_Business_1_0_0,
               PostgreSQL,
               Python_2_0,
               QPL_1_0,
               Qhull,
               RHeCos_1_1,
               RPL_1_1,
               RPL_1_5,
               RPSL_1_0,
               RSA_MD,
               RSCPL,
               Rdisc,
               Ruby,
               SAX_PD,
               SCEA,
               SGI_B_1_0,
               SGI_B_1_1,
               SGI_B_2_0,
               SHL_0_5,
               SHL_0_51,
               SISSL,
               SISSL_1_2,
               SMLNJ,
               SMPPL,
               SNIA,
               SPL_1_0,
               SSH_OpenSSH,
               SSH_short,
               SSPL_1_0,
               SWL,
               Saxpath,
               Sendmail,
               Sendmail_8_23,
               SimPL_2_0,
               Sleepycat,
               Spencer_86,
               Spencer_94,
               Spencer_99,
               SugarCRM_1_1_3,
               TAPR_OHL_1_0,
               TCL,
               TCP_wrappers,
               TMate,
               TORQUE_1_1,
               TOSL,
               TU_Berlin_1_0,
               TU_Berlin_2_0,
               UCL_1_0,
               UPL_1_0,
               Unicode_DFS_2015,
               Unicode_DFS_2016,
               Unicode_TOU,
               Unlicense,
               VOSTROM,
               VSL_1_0,
               Vim,
               W3C,
               W3C_19980720,
               W3C_20150513,
               WTFPL,
               Watcom_1_0,
               Wsuipa,
               X11,
               XFree86_1_1,
               XSkat,
               Xerox,
               Xnet,
               YPL_1_0,
               YPL_1_1,
               ZPL_1_1,
               ZPL_2_0,
               ZPL_2_1,
               Zed,
               Zend_2_0,
               Zimbra_1_3,
               Zimbra_1_4,
               Zlib,
               blessing,
               bzip2_1_0_5,
               bzip2_1_0_6,
               copyleft_next_0_3_0,
               copyleft_next_0_3_1,
               curl,
               diffmark,
               dvipdfm,
               eGenix,
               etalab_2_0,
               gSOAP_1_3b,
               gnuplot,
               iMatix,
               libpng_2_0,
               libselinux_1_0,
               libtiff,
               mpich2,
               psfrag,
               psutils,
               xinetd,
               xpp,
               zlib_acknowledgement);

   type String_Access is not null access constant String;
   Img_Ptr : constant array (Id) of String_Access :=
     (
      Id_0BSD => new String'("0BSD"),
      AAL => new String'("AAL"),
      ADSL => new String'("ADSL"),
      AFL_1_1 => new String'("AFL-1.1"),
      AFL_1_2 => new String'("AFL-1.2"),
      AFL_2_0 => new String'("AFL-2.0"),
      AFL_2_1 => new String'("AFL-2.1"),
      AFL_3_0 => new String'("AFL-3.0"),
      AGPL_1_0_only => new String'("AGPL-1.0-only"),
      AGPL_1_0_or_later => new String'("AGPL-1.0-or-later"),
      AGPL_3_0_only => new String'("AGPL-3.0-only"),
      AGPL_3_0_or_later => new String'("AGPL-3.0-or-later"),
      AMDPLPA => new String'("AMDPLPA"),
      AML => new String'("AML"),
      AMPAS => new String'("AMPAS"),
      ANTLR_PD => new String'("ANTLR-PD"),
      APAFML => new String'("APAFML"),
      APL_1_0 => new String'("APL-1.0"),
      APSL_1_0 => new String'("APSL-1.0"),
      APSL_1_1 => new String'("APSL-1.1"),
      APSL_1_2 => new String'("APSL-1.2"),
      APSL_2_0 => new String'("APSL-2.0"),
      Abstyles => new String'("Abstyles"),
      Adobe_2006 => new String'("Adobe-2006"),
      Adobe_Glyph => new String'("Adobe-Glyph"),
      Afmparse => new String'("Afmparse"),
      Aladdin => new String'("Aladdin"),
      Apache_1_0 => new String'("Apache-1.0"),
      Apache_1_1 => new String'("Apache-1.1"),
      Apache_2_0 => new String'("Apache-2.0"),
      Artistic_1_0 => new String'("Artistic-1.0"),
      Artistic_1_0_Perl => new String'("Artistic-1.0-Perl"),
      Artistic_1_0_cl8 => new String'("Artistic-1.0-cl8"),
      Artistic_2_0 => new String'("Artistic-2.0"),
      BSD_1_Clause => new String'("BSD-1-Clause"),
      BSD_2_Clause => new String'("BSD-2-Clause"),
      BSD_2_Clause_Patent => new String'("BSD-2-Clause-Patent"),
      BSD_2_Clause_Views => new String'("BSD-2-Clause-Views"),
      BSD_3_Clause => new String'("BSD-3-Clause"),
      BSD_3_Clause_Attribution => new String'("BSD-3-Clause-Attribution"),
      BSD_3_Clause_Clear => new String'("BSD-3-Clause-Clear"),
      BSD_3_Clause_LBNL => new String'("BSD-3-Clause-LBNL"),
      BSD_3_Clause_No_Nuclear_License => new String'("BSD-3-Clause-No-Nuclear-License"),
      BSD_3_Clause_No_Nuclear_License_2014 => new String'("BSD-3-Clause-No-Nuclear-License-2014"),
      BSD_3_Clause_No_Nuclear_Warranty => new String'("BSD-3-Clause-No-Nuclear-Warranty"),
      BSD_3_Clause_Open_MPI => new String'("BSD-3-Clause-Open-MPI"),
      BSD_4_Clause => new String'("BSD-4-Clause"),
      BSD_4_Clause_UC => new String'("BSD-4-Clause-UC"),
      BSD_Protection => new String'("BSD-Protection"),
      BSD_Source_Code => new String'("BSD-Source-Code"),
      BSL_1_0 => new String'("BSL-1.0"),
      Bahyph => new String'("Bahyph"),
      Barr => new String'("Barr"),
      Beerware => new String'("Beerware"),
      BitTorrent_1_0 => new String'("BitTorrent-1.0"),
      BitTorrent_1_1 => new String'("BitTorrent-1.1"),
      BlueOak_1_0_0 => new String'("BlueOak-1.0.0"),
      Borceux => new String'("Borceux"),
      CAL_1_0 => new String'("CAL-1.0"),
      CAL_1_0_Combined_Work_Exception => new String'("CAL-1.0-Combined-Work-Exception"),
      CATOSL_1_1 => new String'("CATOSL-1.1"),
      CC_BY_1_0 => new String'("CC-BY-1.0"),
      CC_BY_2_0 => new String'("CC-BY-2.0"),
      CC_BY_2_5 => new String'("CC-BY-2.5"),
      CC_BY_3_0 => new String'("CC-BY-3.0"),
      CC_BY_3_0_AT => new String'("CC-BY-3.0-AT"),
      CC_BY_4_0 => new String'("CC-BY-4.0"),
      CC_BY_NC_1_0 => new String'("CC-BY-NC-1.0"),
      CC_BY_NC_2_0 => new String'("CC-BY-NC-2.0"),
      CC_BY_NC_2_5 => new String'("CC-BY-NC-2.5"),
      CC_BY_NC_3_0 => new String'("CC-BY-NC-3.0"),
      CC_BY_NC_4_0 => new String'("CC-BY-NC-4.0"),
      CC_BY_NC_ND_1_0 => new String'("CC-BY-NC-ND-1.0"),
      CC_BY_NC_ND_2_0 => new String'("CC-BY-NC-ND-2.0"),
      CC_BY_NC_ND_2_5 => new String'("CC-BY-NC-ND-2.5"),
      CC_BY_NC_ND_3_0 => new String'("CC-BY-NC-ND-3.0"),
      CC_BY_NC_ND_3_0_IGO => new String'("CC-BY-NC-ND-3.0-IGO"),
      CC_BY_NC_ND_4_0 => new String'("CC-BY-NC-ND-4.0"),
      CC_BY_NC_SA_1_0 => new String'("CC-BY-NC-SA-1.0"),
      CC_BY_NC_SA_2_0 => new String'("CC-BY-NC-SA-2.0"),
      CC_BY_NC_SA_2_5 => new String'("CC-BY-NC-SA-2.5"),
      CC_BY_NC_SA_3_0 => new String'("CC-BY-NC-SA-3.0"),
      CC_BY_NC_SA_4_0 => new String'("CC-BY-NC-SA-4.0"),
      CC_BY_ND_1_0 => new String'("CC-BY-ND-1.0"),
      CC_BY_ND_2_0 => new String'("CC-BY-ND-2.0"),
      CC_BY_ND_2_5 => new String'("CC-BY-ND-2.5"),
      CC_BY_ND_3_0 => new String'("CC-BY-ND-3.0"),
      CC_BY_ND_4_0 => new String'("CC-BY-ND-4.0"),
      CC_BY_SA_1_0 => new String'("CC-BY-SA-1.0"),
      CC_BY_SA_2_0 => new String'("CC-BY-SA-2.0"),
      CC_BY_SA_2_5 => new String'("CC-BY-SA-2.5"),
      CC_BY_SA_3_0 => new String'("CC-BY-SA-3.0"),
      CC_BY_SA_3_0_AT => new String'("CC-BY-SA-3.0-AT"),
      CC_BY_SA_4_0 => new String'("CC-BY-SA-4.0"),
      CC_PDDC => new String'("CC-PDDC"),
      CC0_1_0 => new String'("CC0-1.0"),
      CDDL_1_0 => new String'("CDDL-1.0"),
      CDDL_1_1 => new String'("CDDL-1.1"),
      CDLA_Permissive_1_0 => new String'("CDLA-Permissive-1.0"),
      CDLA_Sharing_1_0 => new String'("CDLA-Sharing-1.0"),
      CECILL_1_0 => new String'("CECILL-1.0"),
      CECILL_1_1 => new String'("CECILL-1.1"),
      CECILL_2_0 => new String'("CECILL-2.0"),
      CECILL_2_1 => new String'("CECILL-2.1"),
      CECILL_B => new String'("CECILL-B"),
      CECILL_C => new String'("CECILL-C"),
      CERN_OHL_1_1 => new String'("CERN-OHL-1.1"),
      CERN_OHL_1_2 => new String'("CERN-OHL-1.2"),
      CERN_OHL_P_2_0 => new String'("CERN-OHL-P-2.0"),
      CERN_OHL_S_2_0 => new String'("CERN-OHL-S-2.0"),
      CERN_OHL_W_2_0 => new String'("CERN-OHL-W-2.0"),
      CNRI_Jython => new String'("CNRI-Jython"),
      CNRI_Python => new String'("CNRI-Python"),
      CNRI_Python_GPL_Compatible => new String'("CNRI-Python-GPL-Compatible"),
      CPAL_1_0 => new String'("CPAL-1.0"),
      CPL_1_0 => new String'("CPL-1.0"),
      CPOL_1_02 => new String'("CPOL-1.02"),
      CUA_OPL_1_0 => new String'("CUA-OPL-1.0"),
      Caldera => new String'("Caldera"),
      ClArtistic => new String'("ClArtistic"),
      Condor_1_1 => new String'("Condor-1.1"),
      Crossword => new String'("Crossword"),
      CrystalStacker => new String'("CrystalStacker"),
      Cube => new String'("Cube"),
      D_FSL_1_0 => new String'("D-FSL-1.0"),
      DOC => new String'("DOC"),
      DSDP => new String'("DSDP"),
      Dotseqn => new String'("Dotseqn"),
      ECL_1_0 => new String'("ECL-1.0"),
      ECL_2_0 => new String'("ECL-2.0"),
      EFL_1_0 => new String'("EFL-1.0"),
      EFL_2_0 => new String'("EFL-2.0"),
      EPICS => new String'("EPICS"),
      EPL_1_0 => new String'("EPL-1.0"),
      EPL_2_0 => new String'("EPL-2.0"),
      EUDatagrid => new String'("EUDatagrid"),
      EUPL_1_0 => new String'("EUPL-1.0"),
      EUPL_1_1 => new String'("EUPL-1.1"),
      EUPL_1_2 => new String'("EUPL-1.2"),
      Entessa => new String'("Entessa"),
      ErlPL_1_1 => new String'("ErlPL-1.1"),
      Eurosym => new String'("Eurosym"),
      FSFAP => new String'("FSFAP"),
      FSFUL => new String'("FSFUL"),
      FSFULLR => new String'("FSFULLR"),
      FTL => new String'("FTL"),
      Fair => new String'("Fair"),
      Frameworx_1_0 => new String'("Frameworx-1.0"),
      FreeImage => new String'("FreeImage"),
      GFDL_1_1_invariants_only => new String'("GFDL-1.1-invariants-only"),
      GFDL_1_1_invariants_or_later => new String'("GFDL-1.1-invariants-or-later"),
      GFDL_1_1_no_invariants_only => new String'("GFDL-1.1-no-invariants-only"),
      GFDL_1_1_no_invariants_or_later => new String'("GFDL-1.1-no-invariants-or-later"),
      GFDL_1_1_only => new String'("GFDL-1.1-only"),
      GFDL_1_1_or_later => new String'("GFDL-1.1-or-later"),
      GFDL_1_2_invariants_only => new String'("GFDL-1.2-invariants-only"),
      GFDL_1_2_invariants_or_later => new String'("GFDL-1.2-invariants-or-later"),
      GFDL_1_2_no_invariants_only => new String'("GFDL-1.2-no-invariants-only"),
      GFDL_1_2_no_invariants_or_later => new String'("GFDL-1.2-no-invariants-or-later"),
      GFDL_1_2_only => new String'("GFDL-1.2-only"),
      GFDL_1_2_or_later => new String'("GFDL-1.2-or-later"),
      GFDL_1_3_invariants_only => new String'("GFDL-1.3-invariants-only"),
      GFDL_1_3_invariants_or_later => new String'("GFDL-1.3-invariants-or-later"),
      GFDL_1_3_no_invariants_only => new String'("GFDL-1.3-no-invariants-only"),
      GFDL_1_3_no_invariants_or_later => new String'("GFDL-1.3-no-invariants-or-later"),
      GFDL_1_3_only => new String'("GFDL-1.3-only"),
      GFDL_1_3_or_later => new String'("GFDL-1.3-or-later"),
      GL2PS => new String'("GL2PS"),
      GLWTPL => new String'("GLWTPL"),
      GPL_1_0_only => new String'("GPL-1.0-only"),
      GPL_1_0_or_later => new String'("GPL-1.0-or-later"),
      GPL_2_0_only => new String'("GPL-2.0-only"),
      GPL_2_0_or_later => new String'("GPL-2.0-or-later"),
      GPL_3_0_only => new String'("GPL-3.0-only"),
      GPL_3_0_or_later => new String'("GPL-3.0-or-later"),
      Giftware => new String'("Giftware"),
      Glide => new String'("Glide"),
      Glulxe => new String'("Glulxe"),
      HPND => new String'("HPND"),
      HPND_sell_variant => new String'("HPND-sell-variant"),
      HaskellReport => new String'("HaskellReport"),
      Hippocratic_2_1 => new String'("Hippocratic-2.1"),
      IBM_pibs => new String'("IBM-pibs"),
      ICU => new String'("ICU"),
      IJG => new String'("IJG"),
      IPA => new String'("IPA"),
      IPL_1_0 => new String'("IPL-1.0"),
      ISC => new String'("ISC"),
      ImageMagick => new String'("ImageMagick"),
      Imlib2 => new String'("Imlib2"),
      Info_ZIP => new String'("Info-ZIP"),
      Intel => new String'("Intel"),
      Intel_ACPI => new String'("Intel-ACPI"),
      Interbase_1_0 => new String'("Interbase-1.0"),
      JPNIC => new String'("JPNIC"),
      JSON => new String'("JSON"),
      JasPer_2_0 => new String'("JasPer-2.0"),
      LAL_1_2 => new String'("LAL-1.2"),
      LAL_1_3 => new String'("LAL-1.3"),
      LGPL_2_0_only => new String'("LGPL-2.0-only"),
      LGPL_2_0_or_later => new String'("LGPL-2.0-or-later"),
      LGPL_2_1_only => new String'("LGPL-2.1-only"),
      LGPL_2_1_or_later => new String'("LGPL-2.1-or-later"),
      LGPL_3_0_only => new String'("LGPL-3.0-only"),
      LGPL_3_0_or_later => new String'("LGPL-3.0-or-later"),
      LGPLLR => new String'("LGPLLR"),
      LPL_1_0 => new String'("LPL-1.0"),
      LPL_1_02 => new String'("LPL-1.02"),
      LPPL_1_0 => new String'("LPPL-1.0"),
      LPPL_1_1 => new String'("LPPL-1.1"),
      LPPL_1_2 => new String'("LPPL-1.2"),
      LPPL_1_3a => new String'("LPPL-1.3a"),
      LPPL_1_3c => new String'("LPPL-1.3c"),
      Latex2e => new String'("Latex2e"),
      Leptonica => new String'("Leptonica"),
      LiLiQ_P_1_1 => new String'("LiLiQ-P-1.1"),
      LiLiQ_R_1_1 => new String'("LiLiQ-R-1.1"),
      LiLiQ_Rplus_1_1 => new String'("LiLiQ-Rplus-1.1"),
      Libpng => new String'("Libpng"),
      Linux_OpenIB => new String'("Linux-OpenIB"),
      MIT => new String'("MIT"),
      MIT_0 => new String'("MIT-0"),
      MIT_CMU => new String'("MIT-CMU"),
      MIT_advertising => new String'("MIT-advertising"),
      MIT_enna => new String'("MIT-enna"),
      MIT_feh => new String'("MIT-feh"),
      MITNFA => new String'("MITNFA"),
      MPL_1_0 => new String'("MPL-1.0"),
      MPL_1_1 => new String'("MPL-1.1"),
      MPL_2_0 => new String'("MPL-2.0"),
      MPL_2_0_no_copyleft_exception => new String'("MPL-2.0-no-copyleft-exception"),
      MS_PL => new String'("MS-PL"),
      MS_RL => new String'("MS-RL"),
      MTLL => new String'("MTLL"),
      MakeIndex => new String'("MakeIndex"),
      MirOS => new String'("MirOS"),
      Motosoto => new String'("Motosoto"),
      MulanPSL_1_0 => new String'("MulanPSL-1.0"),
      MulanPSL_2_0 => new String'("MulanPSL-2.0"),
      Multics => new String'("Multics"),
      Mup => new String'("Mup"),
      NASA_1_3 => new String'("NASA-1.3"),
      NBPL_1_0 => new String'("NBPL-1.0"),
      NCGL_UK_2_0 => new String'("NCGL-UK-2.0"),
      NCSA => new String'("NCSA"),
      NGPL => new String'("NGPL"),
      NIST_PD => new String'("NIST-PD"),
      NIST_PD_fallback => new String'("NIST-PD-fallback"),
      NLOD_1_0 => new String'("NLOD-1.0"),
      NLPL => new String'("NLPL"),
      NOSL => new String'("NOSL"),
      NPL_1_0 => new String'("NPL-1.0"),
      NPL_1_1 => new String'("NPL-1.1"),
      NPOSL_3_0 => new String'("NPOSL-3.0"),
      NRL => new String'("NRL"),
      NTP => new String'("NTP"),
      NTP_0 => new String'("NTP-0"),
      Naumen => new String'("Naumen"),
      Net_SNMP => new String'("Net-SNMP"),
      NetCDF => new String'("NetCDF"),
      Newsletr => new String'("Newsletr"),
      Nokia => new String'("Nokia"),
      Noweb => new String'("Noweb"),
      O_UDA_1_0 => new String'("O-UDA-1.0"),
      OCCT_PL => new String'("OCCT-PL"),
      OCLC_2_0 => new String'("OCLC-2.0"),
      ODC_By_1_0 => new String'("ODC-By-1.0"),
      ODbL_1_0 => new String'("ODbL-1.0"),
      OFL_1_0 => new String'("OFL-1.0"),
      OFL_1_0_RFN => new String'("OFL-1.0-RFN"),
      OFL_1_0_no_RFN => new String'("OFL-1.0-no-RFN"),
      OFL_1_1 => new String'("OFL-1.1"),
      OFL_1_1_RFN => new String'("OFL-1.1-RFN"),
      OFL_1_1_no_RFN => new String'("OFL-1.1-no-RFN"),
      OGC_1_0 => new String'("OGC-1.0"),
      OGL_Canada_2_0 => new String'("OGL-Canada-2.0"),
      OGL_UK_1_0 => new String'("OGL-UK-1.0"),
      OGL_UK_2_0 => new String'("OGL-UK-2.0"),
      OGL_UK_3_0 => new String'("OGL-UK-3.0"),
      OGTSL => new String'("OGTSL"),
      OLDAP_1_1 => new String'("OLDAP-1.1"),
      OLDAP_1_2 => new String'("OLDAP-1.2"),
      OLDAP_1_3 => new String'("OLDAP-1.3"),
      OLDAP_1_4 => new String'("OLDAP-1.4"),
      OLDAP_2_0 => new String'("OLDAP-2.0"),
      OLDAP_2_0_1 => new String'("OLDAP-2.0.1"),
      OLDAP_2_1 => new String'("OLDAP-2.1"),
      OLDAP_2_2 => new String'("OLDAP-2.2"),
      OLDAP_2_2_1 => new String'("OLDAP-2.2.1"),
      OLDAP_2_2_2 => new String'("OLDAP-2.2.2"),
      OLDAP_2_3 => new String'("OLDAP-2.3"),
      OLDAP_2_4 => new String'("OLDAP-2.4"),
      OLDAP_2_5 => new String'("OLDAP-2.5"),
      OLDAP_2_6 => new String'("OLDAP-2.6"),
      OLDAP_2_7 => new String'("OLDAP-2.7"),
      OLDAP_2_8 => new String'("OLDAP-2.8"),
      OML => new String'("OML"),
      OPL_1_0 => new String'("OPL-1.0"),
      OSET_PL_2_1 => new String'("OSET-PL-2.1"),
      OSL_1_0 => new String'("OSL-1.0"),
      OSL_1_1 => new String'("OSL-1.1"),
      OSL_2_0 => new String'("OSL-2.0"),
      OSL_2_1 => new String'("OSL-2.1"),
      OSL_3_0 => new String'("OSL-3.0"),
      OpenSSL => new String'("OpenSSL"),
      PDDL_1_0 => new String'("PDDL-1.0"),
      PHP_3_0 => new String'("PHP-3.0"),
      PHP_3_01 => new String'("PHP-3.01"),
      PSF_2_0 => new String'("PSF-2.0"),
      Parity_6_0_0 => new String'("Parity-6.0.0"),
      Parity_7_0_0 => new String'("Parity-7.0.0"),
      Plexus => new String'("Plexus"),
      PolyForm_Noncommercial_1_0_0 => new String'("PolyForm-Noncommercial-1.0.0"),
      PolyForm_Small_Business_1_0_0 => new String'("PolyForm-Small-Business-1.0.0"),
      PostgreSQL => new String'("PostgreSQL"),
      Python_2_0 => new String'("Python-2.0"),
      QPL_1_0 => new String'("QPL-1.0"),
      Qhull => new String'("Qhull"),
      RHeCos_1_1 => new String'("RHeCos-1.1"),
      RPL_1_1 => new String'("RPL-1.1"),
      RPL_1_5 => new String'("RPL-1.5"),
      RPSL_1_0 => new String'("RPSL-1.0"),
      RSA_MD => new String'("RSA-MD"),
      RSCPL => new String'("RSCPL"),
      Rdisc => new String'("Rdisc"),
      Ruby => new String'("Ruby"),
      SAX_PD => new String'("SAX-PD"),
      SCEA => new String'("SCEA"),
      SGI_B_1_0 => new String'("SGI-B-1.0"),
      SGI_B_1_1 => new String'("SGI-B-1.1"),
      SGI_B_2_0 => new String'("SGI-B-2.0"),
      SHL_0_5 => new String'("SHL-0.5"),
      SHL_0_51 => new String'("SHL-0.51"),
      SISSL => new String'("SISSL"),
      SISSL_1_2 => new String'("SISSL-1.2"),
      SMLNJ => new String'("SMLNJ"),
      SMPPL => new String'("SMPPL"),
      SNIA => new String'("SNIA"),
      SPL_1_0 => new String'("SPL-1.0"),
      SSH_OpenSSH => new String'("SSH-OpenSSH"),
      SSH_short => new String'("SSH-short"),
      SSPL_1_0 => new String'("SSPL-1.0"),
      SWL => new String'("SWL"),
      Saxpath => new String'("Saxpath"),
      Sendmail => new String'("Sendmail"),
      Sendmail_8_23 => new String'("Sendmail-8.23"),
      SimPL_2_0 => new String'("SimPL-2.0"),
      Sleepycat => new String'("Sleepycat"),
      Spencer_86 => new String'("Spencer-86"),
      Spencer_94 => new String'("Spencer-94"),
      Spencer_99 => new String'("Spencer-99"),
      SugarCRM_1_1_3 => new String'("SugarCRM-1.1.3"),
      TAPR_OHL_1_0 => new String'("TAPR-OHL-1.0"),
      TCL => new String'("TCL"),
      TCP_wrappers => new String'("TCP-wrappers"),
      TMate => new String'("TMate"),
      TORQUE_1_1 => new String'("TORQUE-1.1"),
      TOSL => new String'("TOSL"),
      TU_Berlin_1_0 => new String'("TU-Berlin-1.0"),
      TU_Berlin_2_0 => new String'("TU-Berlin-2.0"),
      UCL_1_0 => new String'("UCL-1.0"),
      UPL_1_0 => new String'("UPL-1.0"),
      Unicode_DFS_2015 => new String'("Unicode-DFS-2015"),
      Unicode_DFS_2016 => new String'("Unicode-DFS-2016"),
      Unicode_TOU => new String'("Unicode-TOU"),
      Unlicense => new String'("Unlicense"),
      VOSTROM => new String'("VOSTROM"),
      VSL_1_0 => new String'("VSL-1.0"),
      Vim => new String'("Vim"),
      W3C => new String'("W3C"),
      W3C_19980720 => new String'("W3C-19980720"),
      W3C_20150513 => new String'("W3C-20150513"),
      WTFPL => new String'("WTFPL"),
      Watcom_1_0 => new String'("Watcom-1.0"),
      Wsuipa => new String'("Wsuipa"),
      X11 => new String'("X11"),
      XFree86_1_1 => new String'("XFree86-1.1"),
      XSkat => new String'("XSkat"),
      Xerox => new String'("Xerox"),
      Xnet => new String'("Xnet"),
      YPL_1_0 => new String'("YPL-1.0"),
      YPL_1_1 => new String'("YPL-1.1"),
      ZPL_1_1 => new String'("ZPL-1.1"),
      ZPL_2_0 => new String'("ZPL-2.0"),
      ZPL_2_1 => new String'("ZPL-2.1"),
      Zed => new String'("Zed"),
      Zend_2_0 => new String'("Zend-2.0"),
      Zimbra_1_3 => new String'("Zimbra-1.3"),
      Zimbra_1_4 => new String'("Zimbra-1.4"),
      Zlib => new String'("Zlib"),
      blessing => new String'("blessing"),
      bzip2_1_0_5 => new String'("bzip2-1.0.5"),
      bzip2_1_0_6 => new String'("bzip2-1.0.6"),
      copyleft_next_0_3_0 => new String'("copyleft-next-0.3.0"),
      copyleft_next_0_3_1 => new String'("copyleft-next-0.3.1"),
      curl => new String'("curl"),
      diffmark => new String'("diffmark"),
      dvipdfm => new String'("dvipdfm"),
      eGenix => new String'("eGenix"),
      etalab_2_0 => new String'("etalab-2.0"),
      gSOAP_1_3b => new String'("gSOAP-1.3b"),
      gnuplot => new String'("gnuplot"),
      iMatix => new String'("iMatix"),
      libpng_2_0 => new String'("libpng-2.0"),
      libselinux_1_0 => new String'("libselinux-1.0"),
      libtiff => new String'("libtiff"),
      mpich2 => new String'("mpich2"),
      psfrag => new String'("psfrag"),
      psutils => new String'("psutils"),
      xinetd => new String'("xinetd"),
      xpp => new String'("xpp"),
      zlib_acknowledgement => new String'("zlib-acknowledgement"));

   function Img (I : Id) return String
   is (Img_Ptr (I).all);

   Name_Ptr : constant array (Id) of String_Access :=
     (
      Id_0BSD => new String'("BSD Zero Clause License"),
      AAL => new String'("Attribution Assurance License"),
      ADSL => new String'("Amazon Digital Services License"),
      AFL_1_1 => new String'("Academic Free License v1.1"),
      AFL_1_2 => new String'("Academic Free License v1.2"),
      AFL_2_0 => new String'("Academic Free License v2.0"),
      AFL_2_1 => new String'("Academic Free License v2.1"),
      AFL_3_0 => new String'("Academic Free License v3.0"),
      AGPL_1_0_only => new String'("Affero General Public License v1.0 only"),
      AGPL_1_0_or_later => new String'("Affero General Public License v1.0 or later"),
      AGPL_3_0_only => new String'("GNU Affero General Public License v3.0 only"),
      AGPL_3_0_or_later => new String'("GNU Affero General Public License v3.0 or later"),
      AMDPLPA => new String'("AMD's plpa_map.c License"),
      AML => new String'("Apple MIT License"),
      AMPAS => new String'("Academy of Motion Picture Arts and Sciences BSD"),
      ANTLR_PD => new String'("ANTLR Software Rights Notice"),
      APAFML => new String'("Adobe Postscript AFM License"),
      APL_1_0 => new String'("Adaptive Public License 1.0"),
      APSL_1_0 => new String'("Apple Public Source License 1.0"),
      APSL_1_1 => new String'("Apple Public Source License 1.1"),
      APSL_1_2 => new String'("Apple Public Source License 1.2"),
      APSL_2_0 => new String'("Apple Public Source License 2.0"),
      Abstyles => new String'("Abstyles License"),
      Adobe_2006 => new String'("Adobe Systems Incorporated Source Code License Agreement"),
      Adobe_Glyph => new String'("Adobe Glyph List License"),
      Afmparse => new String'("Afmparse License"),
      Aladdin => new String'("Aladdin Free Public License"),
      Apache_1_0 => new String'("Apache License 1.0"),
      Apache_1_1 => new String'("Apache License 1.1"),
      Apache_2_0 => new String'("Apache License 2.0"),
      Artistic_1_0 => new String'("Artistic License 1.0"),
      Artistic_1_0_Perl => new String'("Artistic License 1.0 (Perl)"),
      Artistic_1_0_cl8 => new String'("Artistic License 1.0 w/clause 8"),
      Artistic_2_0 => new String'("Artistic License 2.0"),
      BSD_1_Clause => new String'("BSD 1-Clause License"),
      BSD_2_Clause => new String'("BSD 2-Clause ""Simplified"" License"),
      BSD_2_Clause_Patent => new String'("BSD-2-Clause Plus Patent License"),
      BSD_2_Clause_Views => new String'("BSD 2-Clause with views sentence"),
      BSD_3_Clause => new String'("BSD 3-Clause ""New"" or ""Revised"" License"),
      BSD_3_Clause_Attribution => new String'("BSD with attribution"),
      BSD_3_Clause_Clear => new String'("BSD 3-Clause Clear License"),
      BSD_3_Clause_LBNL => new String'("Lawrence Berkeley National Labs BSD variant license"),
      BSD_3_Clause_No_Nuclear_License => new String'("BSD 3-Clause No Nuclear License"),
      BSD_3_Clause_No_Nuclear_License_2014 => new String'("BSD 3-Clause No Nuclear License 2014"),
      BSD_3_Clause_No_Nuclear_Warranty => new String'("BSD 3-Clause No Nuclear Warranty"),
      BSD_3_Clause_Open_MPI => new String'("BSD 3-Clause Open MPI variant"),
      BSD_4_Clause => new String'("BSD 4-Clause ""Original"" or ""Old"" License"),
      BSD_4_Clause_UC => new String'("BSD-4-Clause (University of California-Specific)"),
      BSD_Protection => new String'("BSD Protection License"),
      BSD_Source_Code => new String'("BSD Source Code Attribution"),
      BSL_1_0 => new String'("Boost Software License 1.0"),
      Bahyph => new String'("Bahyph License"),
      Barr => new String'("Barr License"),
      Beerware => new String'("Beerware License"),
      BitTorrent_1_0 => new String'("BitTorrent Open Source License v1.0"),
      BitTorrent_1_1 => new String'("BitTorrent Open Source License v1.1"),
      BlueOak_1_0_0 => new String'("Blue Oak Model License 1.0.0"),
      Borceux => new String'("Borceux license"),
      CAL_1_0 => new String'("Cryptographic Autonomy License 1.0"),
      CAL_1_0_Combined_Work_Exception => new String'("Cryptographic Autonomy License 1.0 (Combined Work Exception)"),
      CATOSL_1_1 => new String'("Computer Associates Trusted Open Source License 1.1"),
      CC_BY_1_0 => new String'("Creative Commons Attribution 1.0 Generic"),
      CC_BY_2_0 => new String'("Creative Commons Attribution 2.0 Generic"),
      CC_BY_2_5 => new String'("Creative Commons Attribution 2.5 Generic"),
      CC_BY_3_0 => new String'("Creative Commons Attribution 3.0 Unported"),
      CC_BY_3_0_AT => new String'("Creative Commons Attribution 3.0 Austria"),
      CC_BY_4_0 => new String'("Creative Commons Attribution 4.0 International"),
      CC_BY_NC_1_0 => new String'("Creative Commons Attribution Non Commercial 1.0 Generic"),
      CC_BY_NC_2_0 => new String'("Creative Commons Attribution Non Commercial 2.0 Generic"),
      CC_BY_NC_2_5 => new String'("Creative Commons Attribution Non Commercial 2.5 Generic"),
      CC_BY_NC_3_0 => new String'("Creative Commons Attribution Non Commercial 3.0 Unported"),
      CC_BY_NC_4_0 => new String'("Creative Commons Attribution Non Commercial 4.0 International"),
      CC_BY_NC_ND_1_0 => new String'("Creative Commons Attribution Non Commercial No Derivatives 1.0 Generic"),
      CC_BY_NC_ND_2_0 => new String'("Creative Commons Attribution Non Commercial No Derivatives 2.0 Generic"),
      CC_BY_NC_ND_2_5 => new String'("Creative Commons Attribution Non Commercial No Derivatives 2.5 Generic"),
      CC_BY_NC_ND_3_0 => new String'("Creative Commons Attribution Non Commercial No Derivatives 3.0 Unported"),
      CC_BY_NC_ND_3_0_IGO => new String'("Creative Commons Attribution Non Commercial No Derivatives 3.0 IGO"),
      CC_BY_NC_ND_4_0 => new String'("Creative Commons Attribution Non Commercial No Derivatives 4.0 International"),
      CC_BY_NC_SA_1_0 => new String'("Creative Commons Attribution Non Commercial Share Alike 1.0 Generic"),
      CC_BY_NC_SA_2_0 => new String'("Creative Commons Attribution Non Commercial Share Alike 2.0 Generic"),
      CC_BY_NC_SA_2_5 => new String'("Creative Commons Attribution Non Commercial Share Alike 2.5 Generic"),
      CC_BY_NC_SA_3_0 => new String'("Creative Commons Attribution Non Commercial Share Alike 3.0 Unported"),
      CC_BY_NC_SA_4_0 => new String'("Creative Commons Attribution Non Commercial Share Alike 4.0 International"),
      CC_BY_ND_1_0 => new String'("Creative Commons Attribution No Derivatives 1.0 Generic"),
      CC_BY_ND_2_0 => new String'("Creative Commons Attribution No Derivatives 2.0 Generic"),
      CC_BY_ND_2_5 => new String'("Creative Commons Attribution No Derivatives 2.5 Generic"),
      CC_BY_ND_3_0 => new String'("Creative Commons Attribution No Derivatives 3.0 Unported"),
      CC_BY_ND_4_0 => new String'("Creative Commons Attribution No Derivatives 4.0 International"),
      CC_BY_SA_1_0 => new String'("Creative Commons Attribution Share Alike 1.0 Generic"),
      CC_BY_SA_2_0 => new String'("Creative Commons Attribution Share Alike 2.0 Generic"),
      CC_BY_SA_2_5 => new String'("Creative Commons Attribution Share Alike 2.5 Generic"),
      CC_BY_SA_3_0 => new String'("Creative Commons Attribution Share Alike 3.0 Unported"),
      CC_BY_SA_3_0_AT => new String'("Creative Commons Attribution-Share Alike 3.0 Austria"),
      CC_BY_SA_4_0 => new String'("Creative Commons Attribution Share Alike 4.0 International"),
      CC_PDDC => new String'("Creative Commons Public Domain Dedication and Certification"),
      CC0_1_0 => new String'("Creative Commons Zero v1.0 Universal"),
      CDDL_1_0 => new String'("Common Development and Distribution License 1.0"),
      CDDL_1_1 => new String'("Common Development and Distribution License 1.1"),
      CDLA_Permissive_1_0 => new String'("Community Data License Agreement Permissive 1.0"),
      CDLA_Sharing_1_0 => new String'("Community Data License Agreement Sharing 1.0"),
      CECILL_1_0 => new String'("CeCILL Free Software License Agreement v1.0"),
      CECILL_1_1 => new String'("CeCILL Free Software License Agreement v1.1"),
      CECILL_2_0 => new String'("CeCILL Free Software License Agreement v2.0"),
      CECILL_2_1 => new String'("CeCILL Free Software License Agreement v2.1"),
      CECILL_B => new String'("CeCILL-B Free Software License Agreement"),
      CECILL_C => new String'("CeCILL-C Free Software License Agreement"),
      CERN_OHL_1_1 => new String'("CERN Open Hardware Licence v1.1"),
      CERN_OHL_1_2 => new String'("CERN Open Hardware Licence v1.2"),
      CERN_OHL_P_2_0 => new String'("CERN Open Hardware Licence Version 2 - Permissive"),
      CERN_OHL_S_2_0 => new String'("CERN Open Hardware Licence Version 2 - Strongly Reciprocal"),
      CERN_OHL_W_2_0 => new String'("CERN Open Hardware Licence Version 2 - Weakly Reciprocal"),
      CNRI_Jython => new String'("CNRI Jython License"),
      CNRI_Python => new String'("CNRI Python License"),
      CNRI_Python_GPL_Compatible => new String'("CNRI Python Open Source GPL Compatible License Agreement"),
      CPAL_1_0 => new String'("Common Public Attribution License 1.0"),
      CPL_1_0 => new String'("Common Public License 1.0"),
      CPOL_1_02 => new String'("Code Project Open License 1.02"),
      CUA_OPL_1_0 => new String'("CUA Office Public License v1.0"),
      Caldera => new String'("Caldera License"),
      ClArtistic => new String'("Clarified Artistic License"),
      Condor_1_1 => new String'("Condor Public License v1.1"),
      Crossword => new String'("Crossword License"),
      CrystalStacker => new String'("CrystalStacker License"),
      Cube => new String'("Cube License"),
      D_FSL_1_0 => new String'("Deutsche Freie Software Lizenz"),
      DOC => new String'("DOC License"),
      DSDP => new String'("DSDP License"),
      Dotseqn => new String'("Dotseqn License"),
      ECL_1_0 => new String'("Educational Community License v1.0"),
      ECL_2_0 => new String'("Educational Community License v2.0"),
      EFL_1_0 => new String'("Eiffel Forum License v1.0"),
      EFL_2_0 => new String'("Eiffel Forum License v2.0"),
      EPICS => new String'("EPICS Open License"),
      EPL_1_0 => new String'("Eclipse Public License 1.0"),
      EPL_2_0 => new String'("Eclipse Public License 2.0"),
      EUDatagrid => new String'("EU DataGrid Software License"),
      EUPL_1_0 => new String'("European Union Public License 1.0"),
      EUPL_1_1 => new String'("European Union Public License 1.1"),
      EUPL_1_2 => new String'("European Union Public License 1.2"),
      Entessa => new String'("Entessa Public License v1.0"),
      ErlPL_1_1 => new String'("Erlang Public License v1.1"),
      Eurosym => new String'("Eurosym License"),
      FSFAP => new String'("FSF All Permissive License"),
      FSFUL => new String'("FSF Unlimited License"),
      FSFULLR => new String'("FSF Unlimited License (with License Retention)"),
      FTL => new String'("Freetype Project License"),
      Fair => new String'("Fair License"),
      Frameworx_1_0 => new String'("Frameworx Open License 1.0"),
      FreeImage => new String'("FreeImage Public License v1.0"),
      GFDL_1_1_invariants_only => new String'("GNU Free Documentation License v1.1 only - invariants"),
      GFDL_1_1_invariants_or_later => new String'("GNU Free Documentation License v1.1 or later - invariants"),
      GFDL_1_1_no_invariants_only => new String'("GNU Free Documentation License v1.1 only - no invariants"),
      GFDL_1_1_no_invariants_or_later => new String'("GNU Free Documentation License v1.1 or later - no invariants"),
      GFDL_1_1_only => new String'("GNU Free Documentation License v1.1 only"),
      GFDL_1_1_or_later => new String'("GNU Free Documentation License v1.1 or later"),
      GFDL_1_2_invariants_only => new String'("GNU Free Documentation License v1.2 only - invariants"),
      GFDL_1_2_invariants_or_later => new String'("GNU Free Documentation License v1.2 or later - invariants"),
      GFDL_1_2_no_invariants_only => new String'("GNU Free Documentation License v1.2 only - no invariants"),
      GFDL_1_2_no_invariants_or_later => new String'("GNU Free Documentation License v1.2 or later - no invariants"),
      GFDL_1_2_only => new String'("GNU Free Documentation License v1.2 only"),
      GFDL_1_2_or_later => new String'("GNU Free Documentation License v1.2 or later"),
      GFDL_1_3_invariants_only => new String'("GNU Free Documentation License v1.3 only - invariants"),
      GFDL_1_3_invariants_or_later => new String'("GNU Free Documentation License v1.3 or later - invariants"),
      GFDL_1_3_no_invariants_only => new String'("GNU Free Documentation License v1.3 only - no invariants"),
      GFDL_1_3_no_invariants_or_later => new String'("GNU Free Documentation License v1.3 or later - no invariants"),
      GFDL_1_3_only => new String'("GNU Free Documentation License v1.3 only"),
      GFDL_1_3_or_later => new String'("GNU Free Documentation License v1.3 or later"),
      GL2PS => new String'("GL2PS License"),
      GLWTPL => new String'("Good Luck With That Public License"),
      GPL_1_0_only => new String'("GNU General Public License v1.0 only"),
      GPL_1_0_or_later => new String'("GNU General Public License v1.0 or later"),
      GPL_2_0_only => new String'("GNU General Public License v2.0 only"),
      GPL_2_0_or_later => new String'("GNU General Public License v2.0 or later"),
      GPL_3_0_only => new String'("GNU General Public License v3.0 only"),
      GPL_3_0_or_later => new String'("GNU General Public License v3.0 or later"),
      Giftware => new String'("Giftware License"),
      Glide => new String'("3dfx Glide License"),
      Glulxe => new String'("Glulxe License"),
      HPND => new String'("Historical Permission Notice and Disclaimer"),
      HPND_sell_variant => new String'("Historical Permission Notice and Disclaimer - sell variant"),
      HaskellReport => new String'("Haskell Language Report License"),
      Hippocratic_2_1 => new String'("Hippocratic License 2.1"),
      IBM_pibs => new String'("IBM PowerPC Initialization and Boot Software"),
      ICU => new String'("ICU License"),
      IJG => new String'("Independent JPEG Group License"),
      IPA => new String'("IPA Font License"),
      IPL_1_0 => new String'("IBM Public License v1.0"),
      ISC => new String'("ISC License"),
      ImageMagick => new String'("ImageMagick License"),
      Imlib2 => new String'("Imlib2 License"),
      Info_ZIP => new String'("Info-ZIP License"),
      Intel => new String'("Intel Open Source License"),
      Intel_ACPI => new String'("Intel ACPI Software License Agreement"),
      Interbase_1_0 => new String'("Interbase Public License v1.0"),
      JPNIC => new String'("Japan Network Information Center License"),
      JSON => new String'("JSON License"),
      JasPer_2_0 => new String'("JasPer License"),
      LAL_1_2 => new String'("Licence Art Libre 1.2"),
      LAL_1_3 => new String'("Licence Art Libre 1.3"),
      LGPL_2_0_only => new String'("GNU Library General Public License v2 only"),
      LGPL_2_0_or_later => new String'("GNU Library General Public License v2 or later"),
      LGPL_2_1_only => new String'("GNU Lesser General Public License v2.1 only"),
      LGPL_2_1_or_later => new String'("GNU Lesser General Public License v2.1 or later"),
      LGPL_3_0_only => new String'("GNU Lesser General Public License v3.0 only"),
      LGPL_3_0_or_later => new String'("GNU Lesser General Public License v3.0 or later"),
      LGPLLR => new String'("Lesser General Public License For Linguistic Resources"),
      LPL_1_0 => new String'("Lucent Public License Version 1.0"),
      LPL_1_02 => new String'("Lucent Public License v1.02"),
      LPPL_1_0 => new String'("LaTeX Project Public License v1.0"),
      LPPL_1_1 => new String'("LaTeX Project Public License v1.1"),
      LPPL_1_2 => new String'("LaTeX Project Public License v1.2"),
      LPPL_1_3a => new String'("LaTeX Project Public License v1.3a"),
      LPPL_1_3c => new String'("LaTeX Project Public License v1.3c"),
      Latex2e => new String'("Latex2e License"),
      Leptonica => new String'("Leptonica License"),
      LiLiQ_P_1_1 => new String'("Licence Libre du Qubec  Permissive version 1.1"),
      LiLiQ_R_1_1 => new String'("Licence Libre du Qubec  Rciprocit version 1.1"),
      LiLiQ_Rplus_1_1 => new String'("Licence Libre du Qubec  Rciprocit forte version 1.1"),
      Libpng => new String'("libpng License"),
      Linux_OpenIB => new String'("Linux Kernel Variant of OpenIB.org license"),
      MIT => new String'("MIT License"),
      MIT_0 => new String'("MIT No Attribution"),
      MIT_CMU => new String'("CMU License"),
      MIT_advertising => new String'("Enlightenment License (e16)"),
      MIT_enna => new String'("enna License"),
      MIT_feh => new String'("feh License"),
      MITNFA => new String'("MIT +no-false-attribs license"),
      MPL_1_0 => new String'("Mozilla Public License 1.0"),
      MPL_1_1 => new String'("Mozilla Public License 1.1"),
      MPL_2_0 => new String'("Mozilla Public License 2.0"),
      MPL_2_0_no_copyleft_exception => new String'("Mozilla Public License 2.0 (no copyleft exception)"),
      MS_PL => new String'("Microsoft Public License"),
      MS_RL => new String'("Microsoft Reciprocal License"),
      MTLL => new String'("Matrix Template Library License"),
      MakeIndex => new String'("MakeIndex License"),
      MirOS => new String'("The MirOS Licence"),
      Motosoto => new String'("Motosoto License"),
      MulanPSL_1_0 => new String'("Mulan Permissive Software License, Version 1"),
      MulanPSL_2_0 => new String'("Mulan Permissive Software License, Version 2"),
      Multics => new String'("Multics License"),
      Mup => new String'("Mup License"),
      NASA_1_3 => new String'("NASA Open Source Agreement 1.3"),
      NBPL_1_0 => new String'("Net Boolean Public License v1"),
      NCGL_UK_2_0 => new String'("Non-Commercial Government Licence"),
      NCSA => new String'("University of Illinois/NCSA Open Source License"),
      NGPL => new String'("Nethack General Public License"),
      NIST_PD => new String'("NIST Public Domain Notice"),
      NIST_PD_fallback => new String'("NIST Public Domain Notice with license fallback"),
      NLOD_1_0 => new String'("Norwegian Licence for Open Government Data"),
      NLPL => new String'("No Limit Public License"),
      NOSL => new String'("Netizen Open Source License"),
      NPL_1_0 => new String'("Netscape Public License v1.0"),
      NPL_1_1 => new String'("Netscape Public License v1.1"),
      NPOSL_3_0 => new String'("Non-Profit Open Software License 3.0"),
      NRL => new String'("NRL License"),
      NTP => new String'("NTP License"),
      NTP_0 => new String'("NTP No Attribution"),
      Naumen => new String'("Naumen Public License"),
      Net_SNMP => new String'("Net-SNMP License"),
      NetCDF => new String'("NetCDF license"),
      Newsletr => new String'("Newsletr License"),
      Nokia => new String'("Nokia Open Source License"),
      Noweb => new String'("Noweb License"),
      O_UDA_1_0 => new String'("Open Use of Data Agreement v1.0"),
      OCCT_PL => new String'("Open CASCADE Technology Public License"),
      OCLC_2_0 => new String'("OCLC Research Public License 2.0"),
      ODC_By_1_0 => new String'("Open Data Commons Attribution License v1.0"),
      ODbL_1_0 => new String'("ODC Open Database License v1.0"),
      OFL_1_0 => new String'("SIL Open Font License 1.0"),
      OFL_1_0_RFN => new String'("SIL Open Font License 1.0 with Reserved Font Name"),
      OFL_1_0_no_RFN => new String'("SIL Open Font License 1.0 with no Reserved Font Name"),
      OFL_1_1 => new String'("SIL Open Font License 1.1"),
      OFL_1_1_RFN => new String'("SIL Open Font License 1.1 with Reserved Font Name"),
      OFL_1_1_no_RFN => new String'("SIL Open Font License 1.1 with no Reserved Font Name"),
      OGC_1_0 => new String'("OGC Software License, Version 1.0"),
      OGL_Canada_2_0 => new String'("Open Government Licence - Canada"),
      OGL_UK_1_0 => new String'("Open Government Licence v1.0"),
      OGL_UK_2_0 => new String'("Open Government Licence v2.0"),
      OGL_UK_3_0 => new String'("Open Government Licence v3.0"),
      OGTSL => new String'("Open Group Test Suite License"),
      OLDAP_1_1 => new String'("Open LDAP Public License v1.1"),
      OLDAP_1_2 => new String'("Open LDAP Public License v1.2"),
      OLDAP_1_3 => new String'("Open LDAP Public License v1.3"),
      OLDAP_1_4 => new String'("Open LDAP Public License v1.4"),
      OLDAP_2_0 => new String'("Open LDAP Public License v2.0 (or possibly 2.0A and 2.0B)"),
      OLDAP_2_0_1 => new String'("Open LDAP Public License v2.0.1"),
      OLDAP_2_1 => new String'("Open LDAP Public License v2.1"),
      OLDAP_2_2 => new String'("Open LDAP Public License v2.2"),
      OLDAP_2_2_1 => new String'("Open LDAP Public License v2.2.1"),
      OLDAP_2_2_2 => new String'("Open LDAP Public License 2.2.2"),
      OLDAP_2_3 => new String'("Open LDAP Public License v2.3"),
      OLDAP_2_4 => new String'("Open LDAP Public License v2.4"),
      OLDAP_2_5 => new String'("Open LDAP Public License v2.5"),
      OLDAP_2_6 => new String'("Open LDAP Public License v2.6"),
      OLDAP_2_7 => new String'("Open LDAP Public License v2.7"),
      OLDAP_2_8 => new String'("Open LDAP Public License v2.8"),
      OML => new String'("Open Market License"),
      OPL_1_0 => new String'("Open Public License v1.0"),
      OSET_PL_2_1 => new String'("OSET Public License version 2.1"),
      OSL_1_0 => new String'("Open Software License 1.0"),
      OSL_1_1 => new String'("Open Software License 1.1"),
      OSL_2_0 => new String'("Open Software License 2.0"),
      OSL_2_1 => new String'("Open Software License 2.1"),
      OSL_3_0 => new String'("Open Software License 3.0"),
      OpenSSL => new String'("OpenSSL License"),
      PDDL_1_0 => new String'("ODC Public Domain Dedication & License 1.0"),
      PHP_3_0 => new String'("PHP License v3.0"),
      PHP_3_01 => new String'("PHP License v3.01"),
      PSF_2_0 => new String'("Python Software Foundation License 2.0"),
      Parity_6_0_0 => new String'("The Parity Public License 6.0.0"),
      Parity_7_0_0 => new String'("The Parity Public License 7.0.0"),
      Plexus => new String'("Plexus Classworlds License"),
      PolyForm_Noncommercial_1_0_0 => new String'("PolyForm Noncommercial License 1.0.0"),
      PolyForm_Small_Business_1_0_0 => new String'("PolyForm Small Business License 1.0.0"),
      PostgreSQL => new String'("PostgreSQL License"),
      Python_2_0 => new String'("Python License 2.0"),
      QPL_1_0 => new String'("Q Public License 1.0"),
      Qhull => new String'("Qhull License"),
      RHeCos_1_1 => new String'("Red Hat eCos Public License v1.1"),
      RPL_1_1 => new String'("Reciprocal Public License 1.1"),
      RPL_1_5 => new String'("Reciprocal Public License 1.5"),
      RPSL_1_0 => new String'("RealNetworks Public Source License v1.0"),
      RSA_MD => new String'("RSA Message-Digest License"),
      RSCPL => new String'("Ricoh Source Code Public License"),
      Rdisc => new String'("Rdisc License"),
      Ruby => new String'("Ruby License"),
      SAX_PD => new String'("Sax Public Domain Notice"),
      SCEA => new String'("SCEA Shared Source License"),
      SGI_B_1_0 => new String'("SGI Free Software License B v1.0"),
      SGI_B_1_1 => new String'("SGI Free Software License B v1.1"),
      SGI_B_2_0 => new String'("SGI Free Software License B v2.0"),
      SHL_0_5 => new String'("Solderpad Hardware License v0.5"),
      SHL_0_51 => new String'("Solderpad Hardware License, Version 0.51"),
      SISSL => new String'("Sun Industry Standards Source License v1.1"),
      SISSL_1_2 => new String'("Sun Industry Standards Source License v1.2"),
      SMLNJ => new String'("Standard ML of New Jersey License"),
      SMPPL => new String'("Secure Messaging Protocol Public License"),
      SNIA => new String'("SNIA Public License 1.1"),
      SPL_1_0 => new String'("Sun Public License v1.0"),
      SSH_OpenSSH => new String'("SSH OpenSSH license"),
      SSH_short => new String'("SSH short notice"),
      SSPL_1_0 => new String'("Server Side Public License, v 1"),
      SWL => new String'("Scheme Widget Library (SWL) Software License Agreement"),
      Saxpath => new String'("Saxpath License"),
      Sendmail => new String'("Sendmail License"),
      Sendmail_8_23 => new String'("Sendmail License 8.23"),
      SimPL_2_0 => new String'("Simple Public License 2.0"),
      Sleepycat => new String'("Sleepycat License"),
      Spencer_86 => new String'("Spencer License 86"),
      Spencer_94 => new String'("Spencer License 94"),
      Spencer_99 => new String'("Spencer License 99"),
      SugarCRM_1_1_3 => new String'("SugarCRM Public License v1.1.3"),
      TAPR_OHL_1_0 => new String'("TAPR Open Hardware License v1.0"),
      TCL => new String'("TCL/TK License"),
      TCP_wrappers => new String'("TCP Wrappers License"),
      TMate => new String'("TMate Open Source License"),
      TORQUE_1_1 => new String'("TORQUE v2.5+ Software License v1.1"),
      TOSL => new String'("Trusster Open Source License"),
      TU_Berlin_1_0 => new String'("Technische Universitaet Berlin License 1.0"),
      TU_Berlin_2_0 => new String'("Technische Universitaet Berlin License 2.0"),
      UCL_1_0 => new String'("Upstream Compatibility License v1.0"),
      UPL_1_0 => new String'("Universal Permissive License v1.0"),
      Unicode_DFS_2015 => new String'("Unicode License Agreement - Data Files and Software (2015)"),
      Unicode_DFS_2016 => new String'("Unicode License Agreement - Data Files and Software (2016)"),
      Unicode_TOU => new String'("Unicode Terms of Use"),
      Unlicense => new String'("The Unlicense"),
      VOSTROM => new String'("VOSTROM Public License for Open Source"),
      VSL_1_0 => new String'("Vovida Software License v1.0"),
      Vim => new String'("Vim License"),
      W3C => new String'("W3C Software Notice and License (2002-12-31)"),
      W3C_19980720 => new String'("W3C Software Notice and License (1998-07-20)"),
      W3C_20150513 => new String'("W3C Software Notice and Document License (2015-05-13)"),
      WTFPL => new String'("Do What The F*ck You Want To Public License"),
      Watcom_1_0 => new String'("Sybase Open Watcom Public License 1.0"),
      Wsuipa => new String'("Wsuipa License"),
      X11 => new String'("X11 License"),
      XFree86_1_1 => new String'("XFree86 License 1.1"),
      XSkat => new String'("XSkat License"),
      Xerox => new String'("Xerox License"),
      Xnet => new String'("X.Net License"),
      YPL_1_0 => new String'("Yahoo! Public License v1.0"),
      YPL_1_1 => new String'("Yahoo! Public License v1.1"),
      ZPL_1_1 => new String'("Zope Public License 1.1"),
      ZPL_2_0 => new String'("Zope Public License 2.0"),
      ZPL_2_1 => new String'("Zope Public License 2.1"),
      Zed => new String'("Zed License"),
      Zend_2_0 => new String'("Zend License v2.0"),
      Zimbra_1_3 => new String'("Zimbra Public License v1.3"),
      Zimbra_1_4 => new String'("Zimbra Public License v1.4"),
      Zlib => new String'("zlib License"),
      blessing => new String'("SQLite Blessing"),
      bzip2_1_0_5 => new String'("bzip2 and libbzip2 License v1.0.5"),
      bzip2_1_0_6 => new String'("bzip2 and libbzip2 License v1.0.6"),
      copyleft_next_0_3_0 => new String'("copyleft-next 0.3.0"),
      copyleft_next_0_3_1 => new String'("copyleft-next 0.3.1"),
      curl => new String'("curl License"),
      diffmark => new String'("diffmark license"),
      dvipdfm => new String'("dvipdfm License"),
      eGenix => new String'("eGenix.com Public License 1.1.0"),
      etalab_2_0 => new String'("Etalab Open License 2.0"),
      gSOAP_1_3b => new String'("gSOAP Public License v1.3b"),
      gnuplot => new String'("gnuplot License"),
      iMatix => new String'("iMatix Standard Function Library Agreement"),
      libpng_2_0 => new String'("PNG Reference Library version 2"),
      libselinux_1_0 => new String'("libselinux public domain notice"),
      libtiff => new String'("libtiff License"),
      mpich2 => new String'("mpich2 License"),
      psfrag => new String'("psfrag License"),
      psutils => new String'("psutils License"),
      xinetd => new String'("xinetd License"),
      xpp => new String'("XPP License"),
      zlib_acknowledgement => new String'("zlib/libpng License with Acknowledgement"));

   function Name (I : Id) return String
   is (Name_Ptr (I).all);

   function Valid_Id (Str : String) return Boolean;
   function From_Id (Str : String) return Id;

end SPDX.Licenses;
