package SPDX.Licenses is

   pragma Style_Checks (Off); --  Genrated code

   Version : constant String :="3.10-14-g0fb8a59";

   type Id is (
               Id_0BSD,
               AAL,
               ADSL,
               AFL_1_1,
               AFL_1_2,
               AFL_2_0,
               AFL_2_1,
               AFL_3_0,
               AGPL_1_0_only,
               AGPL_1_0_or_later,
               AGPL_3_0_only,
               AGPL_3_0_or_later,
               AMDPLPA,
               AML,
               AMPAS,
               ANTLR_PD,
               APAFML,
               APL_1_0,
               APSL_1_0,
               APSL_1_1,
               APSL_1_2,
               APSL_2_0,
               Abstyles,
               Adobe_2006,
               Adobe_Glyph,
               Afmparse,
               Aladdin,
               Apache_1_0,
               Apache_1_1,
               Apache_2_0,
               Artistic_1_0,
               Artistic_1_0_Perl,
               Artistic_1_0_cl8,
               Artistic_2_0,
               BSD_1_Clause,
               BSD_2_Clause,
               BSD_2_Clause_Patent,
               BSD_2_Clause_Views,
               BSD_3_Clause,
               BSD_3_Clause_Attribution,
               BSD_3_Clause_Clear,
               BSD_3_Clause_LBNL,
               BSD_3_Clause_No_Nuclear_License,
               BSD_3_Clause_No_Nuclear_License_2014,
               BSD_3_Clause_No_Nuclear_Warranty,
               BSD_3_Clause_Open_MPI,
               BSD_4_Clause,
               BSD_4_Clause_UC,
               BSD_Protection,
               BSD_Source_Code,
               BSL_1_0,
               Bahyph,
               Barr,
               Beerware,
               BitTorrent_1_0,
               BitTorrent_1_1,
               BlueOak_1_0_0,
               Borceux,
               CAL_1_0,
               CAL_1_0_Combined_Work_Exception,
               CATOSL_1_1,
               CC_BY_1_0,
               CC_BY_2_0,
               CC_BY_2_5,
               CC_BY_3_0,
               CC_BY_3_0_AT,
               CC_BY_4_0,
               CC_BY_NC_1_0,
               CC_BY_NC_2_0,
               CC_BY_NC_2_5,
               CC_BY_NC_3_0,
               CC_BY_NC_4_0,
               CC_BY_NC_ND_1_0,
               CC_BY_NC_ND_2_0,
               CC_BY_NC_ND_2_5,
               CC_BY_NC_ND_3_0,
               CC_BY_NC_ND_3_0_IGO,
               CC_BY_NC_ND_4_0,
               CC_BY_NC_SA_1_0,
               CC_BY_NC_SA_2_0,
               CC_BY_NC_SA_2_5,
               CC_BY_NC_SA_3_0,
               CC_BY_NC_SA_4_0,
               CC_BY_ND_1_0,
               CC_BY_ND_2_0,
               CC_BY_ND_2_5,
               CC_BY_ND_3_0,
               CC_BY_ND_4_0,
               CC_BY_SA_1_0,
               CC_BY_SA_2_0,
               CC_BY_SA_2_5,
               CC_BY_SA_3_0,
               CC_BY_SA_3_0_AT,
               CC_BY_SA_4_0,
               CC_PDDC,
               CC0_1_0,
               CDDL_1_0,
               CDDL_1_1,
               CDLA_Permissive_1_0,
               CDLA_Sharing_1_0,
               CECILL_1_0,
               CECILL_1_1,
               CECILL_2_0,
               CECILL_2_1,
               CECILL_B,
               CECILL_C,
               CERN_OHL_1_1,
               CERN_OHL_1_2,
               CERN_OHL_P_2_0,
               CERN_OHL_S_2_0,
               CERN_OHL_W_2_0,
               CNRI_Jython,
               CNRI_Python,
               CNRI_Python_GPL_Compatible,
               CPAL_1_0,
               CPL_1_0,
               CPOL_1_02,
               CUA_OPL_1_0,
               Caldera,
               ClArtistic,
               Condor_1_1,
               Crossword,
               CrystalStacker,
               Cube,
               D_FSL_1_0,
               DOC,
               DSDP,
               Dotseqn,
               ECL_1_0,
               ECL_2_0,
               EFL_1_0,
               EFL_2_0,
               EPICS,
               EPL_1_0,
               EPL_2_0,
               EUDatagrid,
               EUPL_1_0,
               EUPL_1_1,
               EUPL_1_2,
               Entessa,
               ErlPL_1_1,
               Eurosym,
               FSFAP,
               FSFUL,
               FSFULLR,
               FTL,
               Fair,
               Frameworx_1_0,
               FreeImage,
               GFDL_1_1_invariants_only,
               GFDL_1_1_invariants_or_later,
               GFDL_1_1_no_invariants_only,
               GFDL_1_1_no_invariants_or_later,
               GFDL_1_1_only,
               GFDL_1_1_or_later,
               GFDL_1_2_invariants_only,
               GFDL_1_2_invariants_or_later,
               GFDL_1_2_no_invariants_only,
               GFDL_1_2_no_invariants_or_later,
               GFDL_1_2_only,
               GFDL_1_2_or_later,
               GFDL_1_3_invariants_only,
               GFDL_1_3_invariants_or_later,
               GFDL_1_3_no_invariants_only,
               GFDL_1_3_no_invariants_or_later,
               GFDL_1_3_only,
               GFDL_1_3_or_later,
               GL2PS,
               GLWTPL,
               GPL_1_0_only,
               GPL_1_0_or_later,
               GPL_2_0_only,
               GPL_2_0_or_later,
               GPL_3_0_only,
               GPL_3_0_or_later,
               Giftware,
               Glide,
               Glulxe,
               HPND,
               HPND_sell_variant,
               HaskellReport,
               Hippocratic_2_1,
               IBM_pibs,
               ICU,
               IJG,
               IPA,
               IPL_1_0,
               ISC,
               ImageMagick,
               Imlib2,
               Info_ZIP,
               Intel,
               Intel_ACPI,
               Interbase_1_0,
               JPNIC,
               JSON,
               JasPer_2_0,
               LAL_1_2,
               LAL_1_3,
               LGPL_2_0_only,
               LGPL_2_0_or_later,
               LGPL_2_1_only,
               LGPL_2_1_or_later,
               LGPL_3_0_only,
               LGPL_3_0_or_later,
               LGPLLR,
               LPL_1_0,
               LPL_1_02,
               LPPL_1_0,
               LPPL_1_1,
               LPPL_1_2,
               LPPL_1_3a,
               LPPL_1_3c,
               Latex2e,
               Leptonica,
               LiLiQ_P_1_1,
               LiLiQ_R_1_1,
               LiLiQ_Rplus_1_1,
               Libpng,
               Linux_OpenIB,
               MIT,
               MIT_0,
               MIT_CMU,
               MIT_advertising,
               MIT_enna,
               MIT_feh,
               MITNFA,
               MPL_1_0,
               MPL_1_1,
               MPL_2_0,
               MPL_2_0_no_copyleft_exception,
               MS_PL,
               MS_RL,
               MTLL,
               MakeIndex,
               MirOS,
               Motosoto,
               MulanPSL_1_0,
               MulanPSL_2_0,
               Multics,
               Mup,
               NASA_1_3,
               NBPL_1_0,
               NCGL_UK_2_0,
               NCSA,
               NGPL,
               NIST_PD,
               NIST_PD_fallback,
               NLOD_1_0,
               NLPL,
               NOSL,
               NPL_1_0,
               NPL_1_1,
               NPOSL_3_0,
               NRL,
               NTP,
               NTP_0,
               Naumen,
               Net_SNMP,
               NetCDF,
               Newsletr,
               Nokia,
               Noweb,
               O_UDA_1_0,
               OCCT_PL,
               OCLC_2_0,
               ODC_By_1_0,
               ODbL_1_0,
               OFL_1_0,
               OFL_1_0_RFN,
               OFL_1_0_no_RFN,
               OFL_1_1,
               OFL_1_1_RFN,
               OFL_1_1_no_RFN,
               OGC_1_0,
               OGL_Canada_2_0,
               OGL_UK_1_0,
               OGL_UK_2_0,
               OGL_UK_3_0,
               OGTSL,
               OLDAP_1_1,
               OLDAP_1_2,
               OLDAP_1_3,
               OLDAP_1_4,
               OLDAP_2_0,
               OLDAP_2_0_1,
               OLDAP_2_1,
               OLDAP_2_2,
               OLDAP_2_2_1,
               OLDAP_2_2_2,
               OLDAP_2_3,
               OLDAP_2_4,
               OLDAP_2_5,
               OLDAP_2_6,
               OLDAP_2_7,
               OLDAP_2_8,
               OML,
               OPL_1_0,
               OSET_PL_2_1,
               OSL_1_0,
               OSL_1_1,
               OSL_2_0,
               OSL_2_1,
               OSL_3_0,
               OpenSSL,
               PDDL_1_0,
               PHP_3_0,
               PHP_3_01,
               PSF_2_0,
               Parity_6_0_0,
               Parity_7_0_0,
               Plexus,
               PolyForm_Noncommercial_1_0_0,
               PolyForm_Small_Business_1_0_0,
               PostgreSQL,
               Python_2_0,
               QPL_1_0,
               Qhull,
               RHeCos_1_1,
               RPL_1_1,
               RPL_1_5,
               RPSL_1_0,
               RSA_MD,
               RSCPL,
               Rdisc,
               Ruby,
               SAX_PD,
               SCEA,
               SGI_B_1_0,
               SGI_B_1_1,
               SGI_B_2_0,
               SHL_0_5,
               SHL_0_51,
               SISSL,
               SISSL_1_2,
               SMLNJ,
               SMPPL,
               SNIA,
               SPL_1_0,
               SSH_OpenSSH,
               SSH_short,
               SSPL_1_0,
               SWL,
               Saxpath,
               Sendmail,
               Sendmail_8_23,
               SimPL_2_0,
               Sleepycat,
               Spencer_86,
               Spencer_94,
               Spencer_99,
               SugarCRM_1_1_3,
               TAPR_OHL_1_0,
               TCL,
               TCP_wrappers,
               TMate,
               TORQUE_1_1,
               TOSL,
               TU_Berlin_1_0,
               TU_Berlin_2_0,
               UCL_1_0,
               UPL_1_0,
               Unicode_DFS_2015,
               Unicode_DFS_2016,
               Unicode_TOU,
               Unlicense,
               VOSTROM,
               VSL_1_0,
               Vim,
               W3C,
               W3C_19980720,
               W3C_20150513,
               WTFPL,
               Watcom_1_0,
               Wsuipa,
               X11,
               XFree86_1_1,
               XSkat,
               Xerox,
               Xnet,
               YPL_1_0,
               YPL_1_1,
               ZPL_1_1,
               ZPL_2_0,
               ZPL_2_1,
               Zed,
               Zend_2_0,
               Zimbra_1_3,
               Zimbra_1_4,
               Zlib,
               blessing,
               bzip2_1_0_5,
               bzip2_1_0_6,
               copyleft_next_0_3_0,
               copyleft_next_0_3_1,
               curl,
               diffmark,
               dvipdfm,
               eGenix,
               etalab_2_0,
               gSOAP_1_3b,
               gnuplot,
               iMatix,
               libpng_2_0,
               libselinux_1_0,
               libtiff,
               mpich2,
               psfrag,
               psutils,
               xinetd,
               xpp,
               zlib_acknowledgement);

   function Img (I : Id) return String
   is (case I is
          when Id_0BSD => "0BSD",
          when AAL => "AAL",
          when ADSL => "ADSL",
          when AFL_1_1 => "AFL-1.1",
          when AFL_1_2 => "AFL-1.2",
          when AFL_2_0 => "AFL-2.0",
          when AFL_2_1 => "AFL-2.1",
          when AFL_3_0 => "AFL-3.0",
          when AGPL_1_0_only => "AGPL-1.0-only",
          when AGPL_1_0_or_later => "AGPL-1.0-or-later",
          when AGPL_3_0_only => "AGPL-3.0-only",
          when AGPL_3_0_or_later => "AGPL-3.0-or-later",
          when AMDPLPA => "AMDPLPA",
          when AML => "AML",
          when AMPAS => "AMPAS",
          when ANTLR_PD => "ANTLR-PD",
          when APAFML => "APAFML",
          when APL_1_0 => "APL-1.0",
          when APSL_1_0 => "APSL-1.0",
          when APSL_1_1 => "APSL-1.1",
          when APSL_1_2 => "APSL-1.2",
          when APSL_2_0 => "APSL-2.0",
          when Abstyles => "Abstyles",
          when Adobe_2006 => "Adobe-2006",
          when Adobe_Glyph => "Adobe-Glyph",
          when Afmparse => "Afmparse",
          when Aladdin => "Aladdin",
          when Apache_1_0 => "Apache-1.0",
          when Apache_1_1 => "Apache-1.1",
          when Apache_2_0 => "Apache-2.0",
          when Artistic_1_0 => "Artistic-1.0",
          when Artistic_1_0_Perl => "Artistic-1.0-Perl",
          when Artistic_1_0_cl8 => "Artistic-1.0-cl8",
          when Artistic_2_0 => "Artistic-2.0",
          when BSD_1_Clause => "BSD-1-Clause",
          when BSD_2_Clause => "BSD-2-Clause",
          when BSD_2_Clause_Patent => "BSD-2-Clause-Patent",
          when BSD_2_Clause_Views => "BSD-2-Clause-Views",
          when BSD_3_Clause => "BSD-3-Clause",
          when BSD_3_Clause_Attribution => "BSD-3-Clause-Attribution",
          when BSD_3_Clause_Clear => "BSD-3-Clause-Clear",
          when BSD_3_Clause_LBNL => "BSD-3-Clause-LBNL",
          when BSD_3_Clause_No_Nuclear_License => "BSD-3-Clause-No-Nuclear-License",
          when BSD_3_Clause_No_Nuclear_License_2014 => "BSD-3-Clause-No-Nuclear-License-2014",
          when BSD_3_Clause_No_Nuclear_Warranty => "BSD-3-Clause-No-Nuclear-Warranty",
          when BSD_3_Clause_Open_MPI => "BSD-3-Clause-Open-MPI",
          when BSD_4_Clause => "BSD-4-Clause",
          when BSD_4_Clause_UC => "BSD-4-Clause-UC",
          when BSD_Protection => "BSD-Protection",
          when BSD_Source_Code => "BSD-Source-Code",
          when BSL_1_0 => "BSL-1.0",
          when Bahyph => "Bahyph",
          when Barr => "Barr",
          when Beerware => "Beerware",
          when BitTorrent_1_0 => "BitTorrent-1.0",
          when BitTorrent_1_1 => "BitTorrent-1.1",
          when BlueOak_1_0_0 => "BlueOak-1.0.0",
          when Borceux => "Borceux",
          when CAL_1_0 => "CAL-1.0",
          when CAL_1_0_Combined_Work_Exception => "CAL-1.0-Combined-Work-Exception",
          when CATOSL_1_1 => "CATOSL-1.1",
          when CC_BY_1_0 => "CC-BY-1.0",
          when CC_BY_2_0 => "CC-BY-2.0",
          when CC_BY_2_5 => "CC-BY-2.5",
          when CC_BY_3_0 => "CC-BY-3.0",
          when CC_BY_3_0_AT => "CC-BY-3.0-AT",
          when CC_BY_4_0 => "CC-BY-4.0",
          when CC_BY_NC_1_0 => "CC-BY-NC-1.0",
          when CC_BY_NC_2_0 => "CC-BY-NC-2.0",
          when CC_BY_NC_2_5 => "CC-BY-NC-2.5",
          when CC_BY_NC_3_0 => "CC-BY-NC-3.0",
          when CC_BY_NC_4_0 => "CC-BY-NC-4.0",
          when CC_BY_NC_ND_1_0 => "CC-BY-NC-ND-1.0",
          when CC_BY_NC_ND_2_0 => "CC-BY-NC-ND-2.0",
          when CC_BY_NC_ND_2_5 => "CC-BY-NC-ND-2.5",
          when CC_BY_NC_ND_3_0 => "CC-BY-NC-ND-3.0",
          when CC_BY_NC_ND_3_0_IGO => "CC-BY-NC-ND-3.0-IGO",
          when CC_BY_NC_ND_4_0 => "CC-BY-NC-ND-4.0",
          when CC_BY_NC_SA_1_0 => "CC-BY-NC-SA-1.0",
          when CC_BY_NC_SA_2_0 => "CC-BY-NC-SA-2.0",
          when CC_BY_NC_SA_2_5 => "CC-BY-NC-SA-2.5",
          when CC_BY_NC_SA_3_0 => "CC-BY-NC-SA-3.0",
          when CC_BY_NC_SA_4_0 => "CC-BY-NC-SA-4.0",
          when CC_BY_ND_1_0 => "CC-BY-ND-1.0",
          when CC_BY_ND_2_0 => "CC-BY-ND-2.0",
          when CC_BY_ND_2_5 => "CC-BY-ND-2.5",
          when CC_BY_ND_3_0 => "CC-BY-ND-3.0",
          when CC_BY_ND_4_0 => "CC-BY-ND-4.0",
          when CC_BY_SA_1_0 => "CC-BY-SA-1.0",
          when CC_BY_SA_2_0 => "CC-BY-SA-2.0",
          when CC_BY_SA_2_5 => "CC-BY-SA-2.5",
          when CC_BY_SA_3_0 => "CC-BY-SA-3.0",
          when CC_BY_SA_3_0_AT => "CC-BY-SA-3.0-AT",
          when CC_BY_SA_4_0 => "CC-BY-SA-4.0",
          when CC_PDDC => "CC-PDDC",
          when CC0_1_0 => "CC0-1.0",
          when CDDL_1_0 => "CDDL-1.0",
          when CDDL_1_1 => "CDDL-1.1",
          when CDLA_Permissive_1_0 => "CDLA-Permissive-1.0",
          when CDLA_Sharing_1_0 => "CDLA-Sharing-1.0",
          when CECILL_1_0 => "CECILL-1.0",
          when CECILL_1_1 => "CECILL-1.1",
          when CECILL_2_0 => "CECILL-2.0",
          when CECILL_2_1 => "CECILL-2.1",
          when CECILL_B => "CECILL-B",
          when CECILL_C => "CECILL-C",
          when CERN_OHL_1_1 => "CERN-OHL-1.1",
          when CERN_OHL_1_2 => "CERN-OHL-1.2",
          when CERN_OHL_P_2_0 => "CERN-OHL-P-2.0",
          when CERN_OHL_S_2_0 => "CERN-OHL-S-2.0",
          when CERN_OHL_W_2_0 => "CERN-OHL-W-2.0",
          when CNRI_Jython => "CNRI-Jython",
          when CNRI_Python => "CNRI-Python",
          when CNRI_Python_GPL_Compatible => "CNRI-Python-GPL-Compatible",
          when CPAL_1_0 => "CPAL-1.0",
          when CPL_1_0 => "CPL-1.0",
          when CPOL_1_02 => "CPOL-1.02",
          when CUA_OPL_1_0 => "CUA-OPL-1.0",
          when Caldera => "Caldera",
          when ClArtistic => "ClArtistic",
          when Condor_1_1 => "Condor-1.1",
          when Crossword => "Crossword",
          when CrystalStacker => "CrystalStacker",
          when Cube => "Cube",
          when D_FSL_1_0 => "D-FSL-1.0",
          when DOC => "DOC",
          when DSDP => "DSDP",
          when Dotseqn => "Dotseqn",
          when ECL_1_0 => "ECL-1.0",
          when ECL_2_0 => "ECL-2.0",
          when EFL_1_0 => "EFL-1.0",
          when EFL_2_0 => "EFL-2.0",
          when EPICS => "EPICS",
          when EPL_1_0 => "EPL-1.0",
          when EPL_2_0 => "EPL-2.0",
          when EUDatagrid => "EUDatagrid",
          when EUPL_1_0 => "EUPL-1.0",
          when EUPL_1_1 => "EUPL-1.1",
          when EUPL_1_2 => "EUPL-1.2",
          when Entessa => "Entessa",
          when ErlPL_1_1 => "ErlPL-1.1",
          when Eurosym => "Eurosym",
          when FSFAP => "FSFAP",
          when FSFUL => "FSFUL",
          when FSFULLR => "FSFULLR",
          when FTL => "FTL",
          when Fair => "Fair",
          when Frameworx_1_0 => "Frameworx-1.0",
          when FreeImage => "FreeImage",
          when GFDL_1_1_invariants_only => "GFDL-1.1-invariants-only",
          when GFDL_1_1_invariants_or_later => "GFDL-1.1-invariants-or-later",
          when GFDL_1_1_no_invariants_only => "GFDL-1.1-no-invariants-only",
          when GFDL_1_1_no_invariants_or_later => "GFDL-1.1-no-invariants-or-later",
          when GFDL_1_1_only => "GFDL-1.1-only",
          when GFDL_1_1_or_later => "GFDL-1.1-or-later",
          when GFDL_1_2_invariants_only => "GFDL-1.2-invariants-only",
          when GFDL_1_2_invariants_or_later => "GFDL-1.2-invariants-or-later",
          when GFDL_1_2_no_invariants_only => "GFDL-1.2-no-invariants-only",
          when GFDL_1_2_no_invariants_or_later => "GFDL-1.2-no-invariants-or-later",
          when GFDL_1_2_only => "GFDL-1.2-only",
          when GFDL_1_2_or_later => "GFDL-1.2-or-later",
          when GFDL_1_3_invariants_only => "GFDL-1.3-invariants-only",
          when GFDL_1_3_invariants_or_later => "GFDL-1.3-invariants-or-later",
          when GFDL_1_3_no_invariants_only => "GFDL-1.3-no-invariants-only",
          when GFDL_1_3_no_invariants_or_later => "GFDL-1.3-no-invariants-or-later",
          when GFDL_1_3_only => "GFDL-1.3-only",
          when GFDL_1_3_or_later => "GFDL-1.3-or-later",
          when GL2PS => "GL2PS",
          when GLWTPL => "GLWTPL",
          when GPL_1_0_only => "GPL-1.0-only",
          when GPL_1_0_or_later => "GPL-1.0-or-later",
          when GPL_2_0_only => "GPL-2.0-only",
          when GPL_2_0_or_later => "GPL-2.0-or-later",
          when GPL_3_0_only => "GPL-3.0-only",
          when GPL_3_0_or_later => "GPL-3.0-or-later",
          when Giftware => "Giftware",
          when Glide => "Glide",
          when Glulxe => "Glulxe",
          when HPND => "HPND",
          when HPND_sell_variant => "HPND-sell-variant",
          when HaskellReport => "HaskellReport",
          when Hippocratic_2_1 => "Hippocratic-2.1",
          when IBM_pibs => "IBM-pibs",
          when ICU => "ICU",
          when IJG => "IJG",
          when IPA => "IPA",
          when IPL_1_0 => "IPL-1.0",
          when ISC => "ISC",
          when ImageMagick => "ImageMagick",
          when Imlib2 => "Imlib2",
          when Info_ZIP => "Info-ZIP",
          when Intel => "Intel",
          when Intel_ACPI => "Intel-ACPI",
          when Interbase_1_0 => "Interbase-1.0",
          when JPNIC => "JPNIC",
          when JSON => "JSON",
          when JasPer_2_0 => "JasPer-2.0",
          when LAL_1_2 => "LAL-1.2",
          when LAL_1_3 => "LAL-1.3",
          when LGPL_2_0_only => "LGPL-2.0-only",
          when LGPL_2_0_or_later => "LGPL-2.0-or-later",
          when LGPL_2_1_only => "LGPL-2.1-only",
          when LGPL_2_1_or_later => "LGPL-2.1-or-later",
          when LGPL_3_0_only => "LGPL-3.0-only",
          when LGPL_3_0_or_later => "LGPL-3.0-or-later",
          when LGPLLR => "LGPLLR",
          when LPL_1_0 => "LPL-1.0",
          when LPL_1_02 => "LPL-1.02",
          when LPPL_1_0 => "LPPL-1.0",
          when LPPL_1_1 => "LPPL-1.1",
          when LPPL_1_2 => "LPPL-1.2",
          when LPPL_1_3a => "LPPL-1.3a",
          when LPPL_1_3c => "LPPL-1.3c",
          when Latex2e => "Latex2e",
          when Leptonica => "Leptonica",
          when LiLiQ_P_1_1 => "LiLiQ-P-1.1",
          when LiLiQ_R_1_1 => "LiLiQ-R-1.1",
          when LiLiQ_Rplus_1_1 => "LiLiQ-Rplus-1.1",
          when Libpng => "Libpng",
          when Linux_OpenIB => "Linux-OpenIB",
          when MIT => "MIT",
          when MIT_0 => "MIT-0",
          when MIT_CMU => "MIT-CMU",
          when MIT_advertising => "MIT-advertising",
          when MIT_enna => "MIT-enna",
          when MIT_feh => "MIT-feh",
          when MITNFA => "MITNFA",
          when MPL_1_0 => "MPL-1.0",
          when MPL_1_1 => "MPL-1.1",
          when MPL_2_0 => "MPL-2.0",
          when MPL_2_0_no_copyleft_exception => "MPL-2.0-no-copyleft-exception",
          when MS_PL => "MS-PL",
          when MS_RL => "MS-RL",
          when MTLL => "MTLL",
          when MakeIndex => "MakeIndex",
          when MirOS => "MirOS",
          when Motosoto => "Motosoto",
          when MulanPSL_1_0 => "MulanPSL-1.0",
          when MulanPSL_2_0 => "MulanPSL-2.0",
          when Multics => "Multics",
          when Mup => "Mup",
          when NASA_1_3 => "NASA-1.3",
          when NBPL_1_0 => "NBPL-1.0",
          when NCGL_UK_2_0 => "NCGL-UK-2.0",
          when NCSA => "NCSA",
          when NGPL => "NGPL",
          when NIST_PD => "NIST-PD",
          when NIST_PD_fallback => "NIST-PD-fallback",
          when NLOD_1_0 => "NLOD-1.0",
          when NLPL => "NLPL",
          when NOSL => "NOSL",
          when NPL_1_0 => "NPL-1.0",
          when NPL_1_1 => "NPL-1.1",
          when NPOSL_3_0 => "NPOSL-3.0",
          when NRL => "NRL",
          when NTP => "NTP",
          when NTP_0 => "NTP-0",
          when Naumen => "Naumen",
          when Net_SNMP => "Net-SNMP",
          when NetCDF => "NetCDF",
          when Newsletr => "Newsletr",
          when Nokia => "Nokia",
          when Noweb => "Noweb",
          when O_UDA_1_0 => "O-UDA-1.0",
          when OCCT_PL => "OCCT-PL",
          when OCLC_2_0 => "OCLC-2.0",
          when ODC_By_1_0 => "ODC-By-1.0",
          when ODbL_1_0 => "ODbL-1.0",
          when OFL_1_0 => "OFL-1.0",
          when OFL_1_0_RFN => "OFL-1.0-RFN",
          when OFL_1_0_no_RFN => "OFL-1.0-no-RFN",
          when OFL_1_1 => "OFL-1.1",
          when OFL_1_1_RFN => "OFL-1.1-RFN",
          when OFL_1_1_no_RFN => "OFL-1.1-no-RFN",
          when OGC_1_0 => "OGC-1.0",
          when OGL_Canada_2_0 => "OGL-Canada-2.0",
          when OGL_UK_1_0 => "OGL-UK-1.0",
          when OGL_UK_2_0 => "OGL-UK-2.0",
          when OGL_UK_3_0 => "OGL-UK-3.0",
          when OGTSL => "OGTSL",
          when OLDAP_1_1 => "OLDAP-1.1",
          when OLDAP_1_2 => "OLDAP-1.2",
          when OLDAP_1_3 => "OLDAP-1.3",
          when OLDAP_1_4 => "OLDAP-1.4",
          when OLDAP_2_0 => "OLDAP-2.0",
          when OLDAP_2_0_1 => "OLDAP-2.0.1",
          when OLDAP_2_1 => "OLDAP-2.1",
          when OLDAP_2_2 => "OLDAP-2.2",
          when OLDAP_2_2_1 => "OLDAP-2.2.1",
          when OLDAP_2_2_2 => "OLDAP-2.2.2",
          when OLDAP_2_3 => "OLDAP-2.3",
          when OLDAP_2_4 => "OLDAP-2.4",
          when OLDAP_2_5 => "OLDAP-2.5",
          when OLDAP_2_6 => "OLDAP-2.6",
          when OLDAP_2_7 => "OLDAP-2.7",
          when OLDAP_2_8 => "OLDAP-2.8",
          when OML => "OML",
          when OPL_1_0 => "OPL-1.0",
          when OSET_PL_2_1 => "OSET-PL-2.1",
          when OSL_1_0 => "OSL-1.0",
          when OSL_1_1 => "OSL-1.1",
          when OSL_2_0 => "OSL-2.0",
          when OSL_2_1 => "OSL-2.1",
          when OSL_3_0 => "OSL-3.0",
          when OpenSSL => "OpenSSL",
          when PDDL_1_0 => "PDDL-1.0",
          when PHP_3_0 => "PHP-3.0",
          when PHP_3_01 => "PHP-3.01",
          when PSF_2_0 => "PSF-2.0",
          when Parity_6_0_0 => "Parity-6.0.0",
          when Parity_7_0_0 => "Parity-7.0.0",
          when Plexus => "Plexus",
          when PolyForm_Noncommercial_1_0_0 => "PolyForm-Noncommercial-1.0.0",
          when PolyForm_Small_Business_1_0_0 => "PolyForm-Small-Business-1.0.0",
          when PostgreSQL => "PostgreSQL",
          when Python_2_0 => "Python-2.0",
          when QPL_1_0 => "QPL-1.0",
          when Qhull => "Qhull",
          when RHeCos_1_1 => "RHeCos-1.1",
          when RPL_1_1 => "RPL-1.1",
          when RPL_1_5 => "RPL-1.5",
          when RPSL_1_0 => "RPSL-1.0",
          when RSA_MD => "RSA-MD",
          when RSCPL => "RSCPL",
          when Rdisc => "Rdisc",
          when Ruby => "Ruby",
          when SAX_PD => "SAX-PD",
          when SCEA => "SCEA",
          when SGI_B_1_0 => "SGI-B-1.0",
          when SGI_B_1_1 => "SGI-B-1.1",
          when SGI_B_2_0 => "SGI-B-2.0",
          when SHL_0_5 => "SHL-0.5",
          when SHL_0_51 => "SHL-0.51",
          when SISSL => "SISSL",
          when SISSL_1_2 => "SISSL-1.2",
          when SMLNJ => "SMLNJ",
          when SMPPL => "SMPPL",
          when SNIA => "SNIA",
          when SPL_1_0 => "SPL-1.0",
          when SSH_OpenSSH => "SSH-OpenSSH",
          when SSH_short => "SSH-short",
          when SSPL_1_0 => "SSPL-1.0",
          when SWL => "SWL",
          when Saxpath => "Saxpath",
          when Sendmail => "Sendmail",
          when Sendmail_8_23 => "Sendmail-8.23",
          when SimPL_2_0 => "SimPL-2.0",
          when Sleepycat => "Sleepycat",
          when Spencer_86 => "Spencer-86",
          when Spencer_94 => "Spencer-94",
          when Spencer_99 => "Spencer-99",
          when SugarCRM_1_1_3 => "SugarCRM-1.1.3",
          when TAPR_OHL_1_0 => "TAPR-OHL-1.0",
          when TCL => "TCL",
          when TCP_wrappers => "TCP-wrappers",
          when TMate => "TMate",
          when TORQUE_1_1 => "TORQUE-1.1",
          when TOSL => "TOSL",
          when TU_Berlin_1_0 => "TU-Berlin-1.0",
          when TU_Berlin_2_0 => "TU-Berlin-2.0",
          when UCL_1_0 => "UCL-1.0",
          when UPL_1_0 => "UPL-1.0",
          when Unicode_DFS_2015 => "Unicode-DFS-2015",
          when Unicode_DFS_2016 => "Unicode-DFS-2016",
          when Unicode_TOU => "Unicode-TOU",
          when Unlicense => "Unlicense",
          when VOSTROM => "VOSTROM",
          when VSL_1_0 => "VSL-1.0",
          when Vim => "Vim",
          when W3C => "W3C",
          when W3C_19980720 => "W3C-19980720",
          when W3C_20150513 => "W3C-20150513",
          when WTFPL => "WTFPL",
          when Watcom_1_0 => "Watcom-1.0",
          when Wsuipa => "Wsuipa",
          when X11 => "X11",
          when XFree86_1_1 => "XFree86-1.1",
          when XSkat => "XSkat",
          when Xerox => "Xerox",
          when Xnet => "Xnet",
          when YPL_1_0 => "YPL-1.0",
          when YPL_1_1 => "YPL-1.1",
          when ZPL_1_1 => "ZPL-1.1",
          when ZPL_2_0 => "ZPL-2.0",
          when ZPL_2_1 => "ZPL-2.1",
          when Zed => "Zed",
          when Zend_2_0 => "Zend-2.0",
          when Zimbra_1_3 => "Zimbra-1.3",
          when Zimbra_1_4 => "Zimbra-1.4",
          when Zlib => "Zlib",
          when blessing => "blessing",
          when bzip2_1_0_5 => "bzip2-1.0.5",
          when bzip2_1_0_6 => "bzip2-1.0.6",
          when copyleft_next_0_3_0 => "copyleft-next-0.3.0",
          when copyleft_next_0_3_1 => "copyleft-next-0.3.1",
          when curl => "curl",
          when diffmark => "diffmark",
          when dvipdfm => "dvipdfm",
          when eGenix => "eGenix",
          when etalab_2_0 => "etalab-2.0",
          when gSOAP_1_3b => "gSOAP-1.3b",
          when gnuplot => "gnuplot",
          when iMatix => "iMatix",
          when libpng_2_0 => "libpng-2.0",
          when libselinux_1_0 => "libselinux-1.0",
          when libtiff => "libtiff",
          when mpich2 => "mpich2",
          when psfrag => "psfrag",
          when psutils => "psutils",
          when xinetd => "xinetd",
          when xpp => "xpp",
          when zlib_acknowledgement => "zlib-acknowledgement");

   function Name (I : Id) return String
   is (case I is
          when Id_0BSD => "BSD Zero Clause License",
          when AAL => "Attribution Assurance License",
          when ADSL => "Amazon Digital Services License",
          when AFL_1_1 => "Academic Free License v1.1",
          when AFL_1_2 => "Academic Free License v1.2",
          when AFL_2_0 => "Academic Free License v2.0",
          when AFL_2_1 => "Academic Free License v2.1",
          when AFL_3_0 => "Academic Free License v3.0",
          when AGPL_1_0_only => "Affero General Public License v1.0 only",
          when AGPL_1_0_or_later => "Affero General Public License v1.0 or later",
          when AGPL_3_0_only => "GNU Affero General Public License v3.0 only",
          when AGPL_3_0_or_later => "GNU Affero General Public License v3.0 or later",
          when AMDPLPA => "AMD's plpa_map.c License",
          when AML => "Apple MIT License",
          when AMPAS => "Academy of Motion Picture Arts and Sciences BSD",
          when ANTLR_PD => "ANTLR Software Rights Notice",
          when APAFML => "Adobe Postscript AFM License",
          when APL_1_0 => "Adaptive Public License 1.0",
          when APSL_1_0 => "Apple Public Source License 1.0",
          when APSL_1_1 => "Apple Public Source License 1.1",
          when APSL_1_2 => "Apple Public Source License 1.2",
          when APSL_2_0 => "Apple Public Source License 2.0",
          when Abstyles => "Abstyles License",
          when Adobe_2006 => "Adobe Systems Incorporated Source Code License Agreement",
          when Adobe_Glyph => "Adobe Glyph List License",
          when Afmparse => "Afmparse License",
          when Aladdin => "Aladdin Free Public License",
          when Apache_1_0 => "Apache License 1.0",
          when Apache_1_1 => "Apache License 1.1",
          when Apache_2_0 => "Apache License 2.0",
          when Artistic_1_0 => "Artistic License 1.0",
          when Artistic_1_0_Perl => "Artistic License 1.0 (Perl)",
          when Artistic_1_0_cl8 => "Artistic License 1.0 w/clause 8",
          when Artistic_2_0 => "Artistic License 2.0",
          when BSD_1_Clause => "BSD 1-Clause License",
          when BSD_2_Clause => "BSD 2-Clause ""Simplified"" License",
          when BSD_2_Clause_Patent => "BSD-2-Clause Plus Patent License",
          when BSD_2_Clause_Views => "BSD 2-Clause with views sentence",
          when BSD_3_Clause => "BSD 3-Clause ""New"" or ""Revised"" License",
          when BSD_3_Clause_Attribution => "BSD with attribution",
          when BSD_3_Clause_Clear => "BSD 3-Clause Clear License",
          when BSD_3_Clause_LBNL => "Lawrence Berkeley National Labs BSD variant license",
          when BSD_3_Clause_No_Nuclear_License => "BSD 3-Clause No Nuclear License",
          when BSD_3_Clause_No_Nuclear_License_2014 => "BSD 3-Clause No Nuclear License 2014",
          when BSD_3_Clause_No_Nuclear_Warranty => "BSD 3-Clause No Nuclear Warranty",
          when BSD_3_Clause_Open_MPI => "BSD 3-Clause Open MPI variant",
          when BSD_4_Clause => "BSD 4-Clause ""Original"" or ""Old"" License",
          when BSD_4_Clause_UC => "BSD-4-Clause (University of California-Specific)",
          when BSD_Protection => "BSD Protection License",
          when BSD_Source_Code => "BSD Source Code Attribution",
          when BSL_1_0 => "Boost Software License 1.0",
          when Bahyph => "Bahyph License",
          when Barr => "Barr License",
          when Beerware => "Beerware License",
          when BitTorrent_1_0 => "BitTorrent Open Source License v1.0",
          when BitTorrent_1_1 => "BitTorrent Open Source License v1.1",
          when BlueOak_1_0_0 => "Blue Oak Model License 1.0.0",
          when Borceux => "Borceux license",
          when CAL_1_0 => "Cryptographic Autonomy License 1.0",
          when CAL_1_0_Combined_Work_Exception => "Cryptographic Autonomy License 1.0 (Combined Work Exception)",
          when CATOSL_1_1 => "Computer Associates Trusted Open Source License 1.1",
          when CC_BY_1_0 => "Creative Commons Attribution 1.0 Generic",
          when CC_BY_2_0 => "Creative Commons Attribution 2.0 Generic",
          when CC_BY_2_5 => "Creative Commons Attribution 2.5 Generic",
          when CC_BY_3_0 => "Creative Commons Attribution 3.0 Unported",
          when CC_BY_3_0_AT => "Creative Commons Attribution 3.0 Austria",
          when CC_BY_4_0 => "Creative Commons Attribution 4.0 International",
          when CC_BY_NC_1_0 => "Creative Commons Attribution Non Commercial 1.0 Generic",
          when CC_BY_NC_2_0 => "Creative Commons Attribution Non Commercial 2.0 Generic",
          when CC_BY_NC_2_5 => "Creative Commons Attribution Non Commercial 2.5 Generic",
          when CC_BY_NC_3_0 => "Creative Commons Attribution Non Commercial 3.0 Unported",
          when CC_BY_NC_4_0 => "Creative Commons Attribution Non Commercial 4.0 International",
          when CC_BY_NC_ND_1_0 => "Creative Commons Attribution Non Commercial No Derivatives 1.0 Generic",
          when CC_BY_NC_ND_2_0 => "Creative Commons Attribution Non Commercial No Derivatives 2.0 Generic",
          when CC_BY_NC_ND_2_5 => "Creative Commons Attribution Non Commercial No Derivatives 2.5 Generic",
          when CC_BY_NC_ND_3_0 => "Creative Commons Attribution Non Commercial No Derivatives 3.0 Unported",
          when CC_BY_NC_ND_3_0_IGO => "Creative Commons Attribution Non Commercial No Derivatives 3.0 IGO",
          when CC_BY_NC_ND_4_0 => "Creative Commons Attribution Non Commercial No Derivatives 4.0 International",
          when CC_BY_NC_SA_1_0 => "Creative Commons Attribution Non Commercial Share Alike 1.0 Generic",
          when CC_BY_NC_SA_2_0 => "Creative Commons Attribution Non Commercial Share Alike 2.0 Generic",
          when CC_BY_NC_SA_2_5 => "Creative Commons Attribution Non Commercial Share Alike 2.5 Generic",
          when CC_BY_NC_SA_3_0 => "Creative Commons Attribution Non Commercial Share Alike 3.0 Unported",
          when CC_BY_NC_SA_4_0 => "Creative Commons Attribution Non Commercial Share Alike 4.0 International",
          when CC_BY_ND_1_0 => "Creative Commons Attribution No Derivatives 1.0 Generic",
          when CC_BY_ND_2_0 => "Creative Commons Attribution No Derivatives 2.0 Generic",
          when CC_BY_ND_2_5 => "Creative Commons Attribution No Derivatives 2.5 Generic",
          when CC_BY_ND_3_0 => "Creative Commons Attribution No Derivatives 3.0 Unported",
          when CC_BY_ND_4_0 => "Creative Commons Attribution No Derivatives 4.0 International",
          when CC_BY_SA_1_0 => "Creative Commons Attribution Share Alike 1.0 Generic",
          when CC_BY_SA_2_0 => "Creative Commons Attribution Share Alike 2.0 Generic",
          when CC_BY_SA_2_5 => "Creative Commons Attribution Share Alike 2.5 Generic",
          when CC_BY_SA_3_0 => "Creative Commons Attribution Share Alike 3.0 Unported",
          when CC_BY_SA_3_0_AT => "Creative Commons Attribution-Share Alike 3.0 Austria",
          when CC_BY_SA_4_0 => "Creative Commons Attribution Share Alike 4.0 International",
          when CC_PDDC => "Creative Commons Public Domain Dedication and Certification",
          when CC0_1_0 => "Creative Commons Zero v1.0 Universal",
          when CDDL_1_0 => "Common Development and Distribution License 1.0",
          when CDDL_1_1 => "Common Development and Distribution License 1.1",
          when CDLA_Permissive_1_0 => "Community Data License Agreement Permissive 1.0",
          when CDLA_Sharing_1_0 => "Community Data License Agreement Sharing 1.0",
          when CECILL_1_0 => "CeCILL Free Software License Agreement v1.0",
          when CECILL_1_1 => "CeCILL Free Software License Agreement v1.1",
          when CECILL_2_0 => "CeCILL Free Software License Agreement v2.0",
          when CECILL_2_1 => "CeCILL Free Software License Agreement v2.1",
          when CECILL_B => "CeCILL-B Free Software License Agreement",
          when CECILL_C => "CeCILL-C Free Software License Agreement",
          when CERN_OHL_1_1 => "CERN Open Hardware Licence v1.1",
          when CERN_OHL_1_2 => "CERN Open Hardware Licence v1.2",
          when CERN_OHL_P_2_0 => "CERN Open Hardware Licence Version 2 - Permissive",
          when CERN_OHL_S_2_0 => "CERN Open Hardware Licence Version 2 - Strongly Reciprocal",
          when CERN_OHL_W_2_0 => "CERN Open Hardware Licence Version 2 - Weakly Reciprocal",
          when CNRI_Jython => "CNRI Jython License",
          when CNRI_Python => "CNRI Python License",
          when CNRI_Python_GPL_Compatible => "CNRI Python Open Source GPL Compatible License Agreement",
          when CPAL_1_0 => "Common Public Attribution License 1.0",
          when CPL_1_0 => "Common Public License 1.0",
          when CPOL_1_02 => "Code Project Open License 1.02",
          when CUA_OPL_1_0 => "CUA Office Public License v1.0",
          when Caldera => "Caldera License",
          when ClArtistic => "Clarified Artistic License",
          when Condor_1_1 => "Condor Public License v1.1",
          when Crossword => "Crossword License",
          when CrystalStacker => "CrystalStacker License",
          when Cube => "Cube License",
          when D_FSL_1_0 => "Deutsche Freie Software Lizenz",
          when DOC => "DOC License",
          when DSDP => "DSDP License",
          when Dotseqn => "Dotseqn License",
          when ECL_1_0 => "Educational Community License v1.0",
          when ECL_2_0 => "Educational Community License v2.0",
          when EFL_1_0 => "Eiffel Forum License v1.0",
          when EFL_2_0 => "Eiffel Forum License v2.0",
          when EPICS => "EPICS Open License",
          when EPL_1_0 => "Eclipse Public License 1.0",
          when EPL_2_0 => "Eclipse Public License 2.0",
          when EUDatagrid => "EU DataGrid Software License",
          when EUPL_1_0 => "European Union Public License 1.0",
          when EUPL_1_1 => "European Union Public License 1.1",
          when EUPL_1_2 => "European Union Public License 1.2",
          when Entessa => "Entessa Public License v1.0",
          when ErlPL_1_1 => "Erlang Public License v1.1",
          when Eurosym => "Eurosym License",
          when FSFAP => "FSF All Permissive License",
          when FSFUL => "FSF Unlimited License",
          when FSFULLR => "FSF Unlimited License (with License Retention)",
          when FTL => "Freetype Project License",
          when Fair => "Fair License",
          when Frameworx_1_0 => "Frameworx Open License 1.0",
          when FreeImage => "FreeImage Public License v1.0",
          when GFDL_1_1_invariants_only => "GNU Free Documentation License v1.1 only - invariants",
          when GFDL_1_1_invariants_or_later => "GNU Free Documentation License v1.1 or later - invariants",
          when GFDL_1_1_no_invariants_only => "GNU Free Documentation License v1.1 only - no invariants",
          when GFDL_1_1_no_invariants_or_later => "GNU Free Documentation License v1.1 or later - no invariants",
          when GFDL_1_1_only => "GNU Free Documentation License v1.1 only",
          when GFDL_1_1_or_later => "GNU Free Documentation License v1.1 or later",
          when GFDL_1_2_invariants_only => "GNU Free Documentation License v1.2 only - invariants",
          when GFDL_1_2_invariants_or_later => "GNU Free Documentation License v1.2 or later - invariants",
          when GFDL_1_2_no_invariants_only => "GNU Free Documentation License v1.2 only - no invariants",
          when GFDL_1_2_no_invariants_or_later => "GNU Free Documentation License v1.2 or later - no invariants",
          when GFDL_1_2_only => "GNU Free Documentation License v1.2 only",
          when GFDL_1_2_or_later => "GNU Free Documentation License v1.2 or later",
          when GFDL_1_3_invariants_only => "GNU Free Documentation License v1.3 only - invariants",
          when GFDL_1_3_invariants_or_later => "GNU Free Documentation License v1.3 or later - invariants",
          when GFDL_1_3_no_invariants_only => "GNU Free Documentation License v1.3 only - no invariants",
          when GFDL_1_3_no_invariants_or_later => "GNU Free Documentation License v1.3 or later - no invariants",
          when GFDL_1_3_only => "GNU Free Documentation License v1.3 only",
          when GFDL_1_3_or_later => "GNU Free Documentation License v1.3 or later",
          when GL2PS => "GL2PS License",
          when GLWTPL => "Good Luck With That Public License",
          when GPL_1_0_only => "GNU General Public License v1.0 only",
          when GPL_1_0_or_later => "GNU General Public License v1.0 or later",
          when GPL_2_0_only => "GNU General Public License v2.0 only",
          when GPL_2_0_or_later => "GNU General Public License v2.0 or later",
          when GPL_3_0_only => "GNU General Public License v3.0 only",
          when GPL_3_0_or_later => "GNU General Public License v3.0 or later",
          when Giftware => "Giftware License",
          when Glide => "3dfx Glide License",
          when Glulxe => "Glulxe License",
          when HPND => "Historical Permission Notice and Disclaimer",
          when HPND_sell_variant => "Historical Permission Notice and Disclaimer - sell variant",
          when HaskellReport => "Haskell Language Report License",
          when Hippocratic_2_1 => "Hippocratic License 2.1",
          when IBM_pibs => "IBM PowerPC Initialization and Boot Software",
          when ICU => "ICU License",
          when IJG => "Independent JPEG Group License",
          when IPA => "IPA Font License",
          when IPL_1_0 => "IBM Public License v1.0",
          when ISC => "ISC License",
          when ImageMagick => "ImageMagick License",
          when Imlib2 => "Imlib2 License",
          when Info_ZIP => "Info-ZIP License",
          when Intel => "Intel Open Source License",
          when Intel_ACPI => "Intel ACPI Software License Agreement",
          when Interbase_1_0 => "Interbase Public License v1.0",
          when JPNIC => "Japan Network Information Center License",
          when JSON => "JSON License",
          when JasPer_2_0 => "JasPer License",
          when LAL_1_2 => "Licence Art Libre 1.2",
          when LAL_1_3 => "Licence Art Libre 1.3",
          when LGPL_2_0_only => "GNU Library General Public License v2 only",
          when LGPL_2_0_or_later => "GNU Library General Public License v2 or later",
          when LGPL_2_1_only => "GNU Lesser General Public License v2.1 only",
          when LGPL_2_1_or_later => "GNU Lesser General Public License v2.1 or later",
          when LGPL_3_0_only => "GNU Lesser General Public License v3.0 only",
          when LGPL_3_0_or_later => "GNU Lesser General Public License v3.0 or later",
          when LGPLLR => "Lesser General Public License For Linguistic Resources",
          when LPL_1_0 => "Lucent Public License Version 1.0",
          when LPL_1_02 => "Lucent Public License v1.02",
          when LPPL_1_0 => "LaTeX Project Public License v1.0",
          when LPPL_1_1 => "LaTeX Project Public License v1.1",
          when LPPL_1_2 => "LaTeX Project Public License v1.2",
          when LPPL_1_3a => "LaTeX Project Public License v1.3a",
          when LPPL_1_3c => "LaTeX Project Public License v1.3c",
          when Latex2e => "Latex2e License",
          when Leptonica => "Leptonica License",
          when LiLiQ_P_1_1 => "Licence Libre du Qubec  Permissive version 1.1",
          when LiLiQ_R_1_1 => "Licence Libre du Qubec  Rciprocit version 1.1",
          when LiLiQ_Rplus_1_1 => "Licence Libre du Qubec  Rciprocit forte version 1.1",
          when Libpng => "libpng License",
          when Linux_OpenIB => "Linux Kernel Variant of OpenIB.org license",
          when MIT => "MIT License",
          when MIT_0 => "MIT No Attribution",
          when MIT_CMU => "CMU License",
          when MIT_advertising => "Enlightenment License (e16)",
          when MIT_enna => "enna License",
          when MIT_feh => "feh License",
          when MITNFA => "MIT +no-false-attribs license",
          when MPL_1_0 => "Mozilla Public License 1.0",
          when MPL_1_1 => "Mozilla Public License 1.1",
          when MPL_2_0 => "Mozilla Public License 2.0",
          when MPL_2_0_no_copyleft_exception => "Mozilla Public License 2.0 (no copyleft exception)",
          when MS_PL => "Microsoft Public License",
          when MS_RL => "Microsoft Reciprocal License",
          when MTLL => "Matrix Template Library License",
          when MakeIndex => "MakeIndex License",
          when MirOS => "The MirOS Licence",
          when Motosoto => "Motosoto License",
          when MulanPSL_1_0 => "Mulan Permissive Software License, Version 1",
          when MulanPSL_2_0 => "Mulan Permissive Software License, Version 2",
          when Multics => "Multics License",
          when Mup => "Mup License",
          when NASA_1_3 => "NASA Open Source Agreement 1.3",
          when NBPL_1_0 => "Net Boolean Public License v1",
          when NCGL_UK_2_0 => "Non-Commercial Government Licence",
          when NCSA => "University of Illinois/NCSA Open Source License",
          when NGPL => "Nethack General Public License",
          when NIST_PD => "NIST Public Domain Notice",
          when NIST_PD_fallback => "NIST Public Domain Notice with license fallback",
          when NLOD_1_0 => "Norwegian Licence for Open Government Data",
          when NLPL => "No Limit Public License",
          when NOSL => "Netizen Open Source License",
          when NPL_1_0 => "Netscape Public License v1.0",
          when NPL_1_1 => "Netscape Public License v1.1",
          when NPOSL_3_0 => "Non-Profit Open Software License 3.0",
          when NRL => "NRL License",
          when NTP => "NTP License",
          when NTP_0 => "NTP No Attribution",
          when Naumen => "Naumen Public License",
          when Net_SNMP => "Net-SNMP License",
          when NetCDF => "NetCDF license",
          when Newsletr => "Newsletr License",
          when Nokia => "Nokia Open Source License",
          when Noweb => "Noweb License",
          when O_UDA_1_0 => "Open Use of Data Agreement v1.0",
          when OCCT_PL => "Open CASCADE Technology Public License",
          when OCLC_2_0 => "OCLC Research Public License 2.0",
          when ODC_By_1_0 => "Open Data Commons Attribution License v1.0",
          when ODbL_1_0 => "ODC Open Database License v1.0",
          when OFL_1_0 => "SIL Open Font License 1.0",
          when OFL_1_0_RFN => "SIL Open Font License 1.0 with Reserved Font Name",
          when OFL_1_0_no_RFN => "SIL Open Font License 1.0 with no Reserved Font Name",
          when OFL_1_1 => "SIL Open Font License 1.1",
          when OFL_1_1_RFN => "SIL Open Font License 1.1 with Reserved Font Name",
          when OFL_1_1_no_RFN => "SIL Open Font License 1.1 with no Reserved Font Name",
          when OGC_1_0 => "OGC Software License, Version 1.0",
          when OGL_Canada_2_0 => "Open Government Licence - Canada",
          when OGL_UK_1_0 => "Open Government Licence v1.0",
          when OGL_UK_2_0 => "Open Government Licence v2.0",
          when OGL_UK_3_0 => "Open Government Licence v3.0",
          when OGTSL => "Open Group Test Suite License",
          when OLDAP_1_1 => "Open LDAP Public License v1.1",
          when OLDAP_1_2 => "Open LDAP Public License v1.2",
          when OLDAP_1_3 => "Open LDAP Public License v1.3",
          when OLDAP_1_4 => "Open LDAP Public License v1.4",
          when OLDAP_2_0 => "Open LDAP Public License v2.0 (or possibly 2.0A and 2.0B)",
          when OLDAP_2_0_1 => "Open LDAP Public License v2.0.1",
          when OLDAP_2_1 => "Open LDAP Public License v2.1",
          when OLDAP_2_2 => "Open LDAP Public License v2.2",
          when OLDAP_2_2_1 => "Open LDAP Public License v2.2.1",
          when OLDAP_2_2_2 => "Open LDAP Public License 2.2.2",
          when OLDAP_2_3 => "Open LDAP Public License v2.3",
          when OLDAP_2_4 => "Open LDAP Public License v2.4",
          when OLDAP_2_5 => "Open LDAP Public License v2.5",
          when OLDAP_2_6 => "Open LDAP Public License v2.6",
          when OLDAP_2_7 => "Open LDAP Public License v2.7",
          when OLDAP_2_8 => "Open LDAP Public License v2.8",
          when OML => "Open Market License",
          when OPL_1_0 => "Open Public License v1.0",
          when OSET_PL_2_1 => "OSET Public License version 2.1",
          when OSL_1_0 => "Open Software License 1.0",
          when OSL_1_1 => "Open Software License 1.1",
          when OSL_2_0 => "Open Software License 2.0",
          when OSL_2_1 => "Open Software License 2.1",
          when OSL_3_0 => "Open Software License 3.0",
          when OpenSSL => "OpenSSL License",
          when PDDL_1_0 => "ODC Public Domain Dedication & License 1.0",
          when PHP_3_0 => "PHP License v3.0",
          when PHP_3_01 => "PHP License v3.01",
          when PSF_2_0 => "Python Software Foundation License 2.0",
          when Parity_6_0_0 => "The Parity Public License 6.0.0",
          when Parity_7_0_0 => "The Parity Public License 7.0.0",
          when Plexus => "Plexus Classworlds License",
          when PolyForm_Noncommercial_1_0_0 => "PolyForm Noncommercial License 1.0.0",
          when PolyForm_Small_Business_1_0_0 => "PolyForm Small Business License 1.0.0",
          when PostgreSQL => "PostgreSQL License",
          when Python_2_0 => "Python License 2.0",
          when QPL_1_0 => "Q Public License 1.0",
          when Qhull => "Qhull License",
          when RHeCos_1_1 => "Red Hat eCos Public License v1.1",
          when RPL_1_1 => "Reciprocal Public License 1.1",
          when RPL_1_5 => "Reciprocal Public License 1.5",
          when RPSL_1_0 => "RealNetworks Public Source License v1.0",
          when RSA_MD => "RSA Message-Digest License",
          when RSCPL => "Ricoh Source Code Public License",
          when Rdisc => "Rdisc License",
          when Ruby => "Ruby License",
          when SAX_PD => "Sax Public Domain Notice",
          when SCEA => "SCEA Shared Source License",
          when SGI_B_1_0 => "SGI Free Software License B v1.0",
          when SGI_B_1_1 => "SGI Free Software License B v1.1",
          when SGI_B_2_0 => "SGI Free Software License B v2.0",
          when SHL_0_5 => "Solderpad Hardware License v0.5",
          when SHL_0_51 => "Solderpad Hardware License, Version 0.51",
          when SISSL => "Sun Industry Standards Source License v1.1",
          when SISSL_1_2 => "Sun Industry Standards Source License v1.2",
          when SMLNJ => "Standard ML of New Jersey License",
          when SMPPL => "Secure Messaging Protocol Public License",
          when SNIA => "SNIA Public License 1.1",
          when SPL_1_0 => "Sun Public License v1.0",
          when SSH_OpenSSH => "SSH OpenSSH license",
          when SSH_short => "SSH short notice",
          when SSPL_1_0 => "Server Side Public License, v 1",
          when SWL => "Scheme Widget Library (SWL) Software License Agreement",
          when Saxpath => "Saxpath License",
          when Sendmail => "Sendmail License",
          when Sendmail_8_23 => "Sendmail License 8.23",
          when SimPL_2_0 => "Simple Public License 2.0",
          when Sleepycat => "Sleepycat License",
          when Spencer_86 => "Spencer License 86",
          when Spencer_94 => "Spencer License 94",
          when Spencer_99 => "Spencer License 99",
          when SugarCRM_1_1_3 => "SugarCRM Public License v1.1.3",
          when TAPR_OHL_1_0 => "TAPR Open Hardware License v1.0",
          when TCL => "TCL/TK License",
          when TCP_wrappers => "TCP Wrappers License",
          when TMate => "TMate Open Source License",
          when TORQUE_1_1 => "TORQUE v2.5+ Software License v1.1",
          when TOSL => "Trusster Open Source License",
          when TU_Berlin_1_0 => "Technische Universitaet Berlin License 1.0",
          when TU_Berlin_2_0 => "Technische Universitaet Berlin License 2.0",
          when UCL_1_0 => "Upstream Compatibility License v1.0",
          when UPL_1_0 => "Universal Permissive License v1.0",
          when Unicode_DFS_2015 => "Unicode License Agreement - Data Files and Software (2015)",
          when Unicode_DFS_2016 => "Unicode License Agreement - Data Files and Software (2016)",
          when Unicode_TOU => "Unicode Terms of Use",
          when Unlicense => "The Unlicense",
          when VOSTROM => "VOSTROM Public License for Open Source",
          when VSL_1_0 => "Vovida Software License v1.0",
          when Vim => "Vim License",
          when W3C => "W3C Software Notice and License (2002-12-31)",
          when W3C_19980720 => "W3C Software Notice and License (1998-07-20)",
          when W3C_20150513 => "W3C Software Notice and Document License (2015-05-13)",
          when WTFPL => "Do What The F*ck You Want To Public License",
          when Watcom_1_0 => "Sybase Open Watcom Public License 1.0",
          when Wsuipa => "Wsuipa License",
          when X11 => "X11 License",
          when XFree86_1_1 => "XFree86 License 1.1",
          when XSkat => "XSkat License",
          when Xerox => "Xerox License",
          when Xnet => "X.Net License",
          when YPL_1_0 => "Yahoo! Public License v1.0",
          when YPL_1_1 => "Yahoo! Public License v1.1",
          when ZPL_1_1 => "Zope Public License 1.1",
          when ZPL_2_0 => "Zope Public License 2.0",
          when ZPL_2_1 => "Zope Public License 2.1",
          when Zed => "Zed License",
          when Zend_2_0 => "Zend License v2.0",
          when Zimbra_1_3 => "Zimbra Public License v1.3",
          when Zimbra_1_4 => "Zimbra Public License v1.4",
          when Zlib => "zlib License",
          when blessing => "SQLite Blessing",
          when bzip2_1_0_5 => "bzip2 and libbzip2 License v1.0.5",
          when bzip2_1_0_6 => "bzip2 and libbzip2 License v1.0.6",
          when copyleft_next_0_3_0 => "copyleft-next 0.3.0",
          when copyleft_next_0_3_1 => "copyleft-next 0.3.1",
          when curl => "curl License",
          when diffmark => "diffmark license",
          when dvipdfm => "dvipdfm License",
          when eGenix => "eGenix.com Public License 1.1.0",
          when etalab_2_0 => "Etalab Open License 2.0",
          when gSOAP_1_3b => "gSOAP Public License v1.3b",
          when gnuplot => "gnuplot License",
          when iMatix => "iMatix Standard Function Library Agreement",
          when libpng_2_0 => "PNG Reference Library version 2",
          when libselinux_1_0 => "libselinux public domain notice",
          when libtiff => "libtiff License",
          when mpich2 => "mpich2 License",
          when psfrag => "psfrag License",
          when psutils => "psutils License",
          when xinetd => "xinetd License",
          when xpp => "XPP License",
          when zlib_acknowledgement => "zlib/libpng License with Acknowledgement");

   function Valid_Id (Str : String) return Boolean;
   function From_Id (Str : String) return Id;

end SPDX.Licenses;
